// Hilfe-Inhalte fuer account.html (Tabs dashboard, konto, anmelden, gruppe, charaktere).
export default {
  dashboard: {
    title: 'Dashboard',
    anchor: 'dashboard',
    intro: 'Deine Startseite: Dein Event, dein Ticket, deine Charaktere und deine Gruppe auf einen Blick.',
    items: [
      { label: 'Aktualisieren', text: 'Lädt Event, Charaktere und Anmeldungen neu. Nutze das, wenn sich etwas geändert haben könnte (z. B. Zahlungsstatus).' },
      { label: 'Neues Ticket buchen', text: 'Springt zum Tab „Anmelden“. Der Button erscheint nur, wenn du für das aktive Event schon angemeldet bist.' },
      { label: 'Konto vervollständigen', text: 'Erscheint in einer Hinweis-Karte oben, wenn in deinem Konto noch Pflichtangaben fehlen. Die Karte nennt, was fehlt, und der Button führt dich zum Tab „Konto“.' },
      { label: 'Event-Karte', text: 'Zeigt das aktuell geöffnete Event mit Name, Status deiner Anmeldung, Veranstaltungs-Code, Countdown in Tagen und Datum. Gibt es kein geöffnetes Event, steht dort ein entsprechender Hinweis.' },
      { label: 'Überweisungen prüfen (Karte, nur mit Mitglieder-Menü)', text: 'Erscheint, wenn jemand vor mehr als drei Tagen „Ich habe überwiesen“ gemeldet hat und noch keine Zahlung gebucht ist. Die Liste nennt Person, Event und Tage. Prüfe das Bankkonto und markiere die Zahlung im Check-In als bezahlt, oder setze die Meldung in den Mitgliedern zurück.' },
      { label: 'Ich habe überwiesen', text: 'Nach dem Klick verschwindet der Button und es steht „Überweisung gemeldet“. Hat die Orga keinen Eingang gefunden, setzt sie die Meldung zurück, dann kannst du erneut melden. Im Zahlungsdialog, sobald eine Bankverbindung eingerichtet ist. Meldet der Orga, dass du überwiesen hast, damit sie den Kontoeingang bald prüft. Es markiert nichts als bezahlt; das tut die Orga nach Prüfung. Danach steht auf dem Dashboard „Überweisung gemeldet“.' },
      { label: 'Für {Event} anmelden', text: 'Erscheint in der Event-Karte, solange du noch nicht angemeldet bist, und führt zum Tab „Anmelden“. Bist du angemeldet, steht dort stattdessen dein Status (angemeldet, Warteliste oder abgesagt).' },
      { label: 'Jetzt bezahlen', text: 'Erscheint in der Event-Karte nur, wenn für deine Anmeldung noch ein Betrag offen ist, du kein Con-Zahler bist und die Orga die Zahlungen freigegeben hat. Öffnet den Zahlungsdialog.' },
      { label: 'Ort: Google Maps / OpenStreetMap', text: 'Zeigt die Adresse des Events und öffnet sie in einem neuen Tab im jeweiligen Kartendienst. Erscheint nur, wenn die Orga eine Adresse oder einen Kartenlink hinterlegt hat.' },
      { label: 'Anfahrtsbeschreibung', text: 'Öffnet ein Fenster mit der Anfahrtsbeschreibung. Der Button erscheint nur, wenn die Orga einen Text dafür hinterlegt hat.' },
      { label: 'Plot & Briefing', text: 'Öffnet ein Fenster mit dem Plot- und Briefing-Text zum Event. Der Button erscheint nur, wenn die Orga einen Text hinterlegt hat.' },
      { label: 'Dialog: Anfahrtsbeschreibung / Plot & Briefing', text: 'Reines Lesefenster. „Schließen“ macht es wieder zu, es wird nichts gespeichert.' },
      { label: 'Tavernenkonto', text: 'Karte mit deinem Guthaben und deiner Tavernen-Nummer. Sie erscheint nur, wenn die Orga das Tavernenkonto aktiviert hat und du ein Konto für das aktive Event hast. Ist das Konto gesperrt, wird „Gesperrt“ angezeigt und es gibt keinen Aufladen-Button.' },
      { label: 'Aufladen', text: 'Öffnet den Dialog zum Aufladen deines Tavernenkontos.' },
      { label: 'Dialog: Tavernenkonto aufladen', text: 'Gib einen Betrag von 5 bis 200 Euro ein und wähle „Per PayPal“, „Per Kreditkarte“ oder „Per Banküberweisung“ (dauert 1–2 Werktage). Du wirst zum Zahlungsanbieter weitergeleitet; das Guthaben wird gutgeschrieben, sobald die Zahlung bei uns eingegangen ist. „Schließen“ bricht ab.' },
      { label: 'Einladung zu einer Gruppe (Annehmen / Ablehnen)', text: 'Wenn dich jemand in seine Gruppe eingeladen hat, erscheint oben eine Karte. Wenn du annimmst, sieht der Gruppenverwalter deine Gruppe, bearbeitet die für ihn freigegebenen Felder und kann dich und deine Personen zu Events anmelden. „Ablehnen“ weist die Einladung zurück.' },
      { label: 'Änderungen an deinen Daten prüfen', text: 'Hat jemand anderes (z. B. ein Gruppenverwalter oder die Orga) Daten deines Kontos, deines Charakters oder NSC-Profils geändert, siehst du hier jede Änderung mit „alt → neu“. Du setzt Haken bei dem, was bleiben soll.' },
      { label: 'Auswahl übernehmen', text: 'Übernimmt die angehakten Änderungen. Alles, was nicht angehakt ist, wird auf den alten Wert zurückgesetzt.' },
      { label: 'Alle auswählen / Alle abwählen', text: 'Setzt oder entfernt alle Haken einer Änderungsanfrage auf einmal.' },
      { label: 'Meine Charaktere', text: 'Liste deiner Charaktere mit Bild, Name und der Angabe, ob und für welches Event sie angemeldet sind. Ein Klick auf einen Charakter führt zum Tab „Charaktere“.' },
      { label: 'Neuen Charakter anlegen', text: 'Springt zum Tab „Charaktere“ und öffnet gleich das leere Formular für einen neuen Charakter.' },
      { label: 'Alle Charaktere verwalten', text: 'Springt zum Tab „Charaktere“.' },
      { label: 'Gruppe oder weitere Charaktere anmelden (Schalter)', text: 'Nur sichtbar, solange du noch niemanden in deiner Gruppe hast. Schaltest du ihn ein, erscheint der Menüpunkt „Gruppe“ in der Seitenleiste und du landest dort. Ausschalten blendet den Menüpunkt wieder aus, sofern du keine Personen oder Mitglieder hast.' },
      { label: 'Verwaltete Personen / Zur Gruppenverwaltung', text: 'Karte mit der Zahl deiner verwalteten Personen, Mitglieder und offenen Einladungen. Sie erscheint nur, wenn du schon Personen oder eine Gruppe hast. Der Button führt zum Tab „Gruppe“.' },
      { label: 'Dein Event-Ticket', text: 'Rechte Karte mit deinem Ticket und QR-Code zum Vorzeigen am Check-In. Du siehst Event, Teilnehmer, Rolle und Datum. Das Ticket erscheint erst, wenn eine Anmeldung besteht, das Event einen Code hat und die Zahlung bestätigt ist.' },
      { label: 'Hinweise im Ticket-Bereich', text: 'Statt des Tickets steht dort, was fehlt: kein Event geöffnet, noch kein QR-Code eingerichtet, du bist nicht angemeldet, der Betrag ist noch nicht festgelegt oder die Zahlung ist offen (mit Betrag). Als Con-Zahler zahlst du vor Ort beim Check-In, dein Ticket ist trotzdem gültig und trägt den Vermerk „Con-Zahler“.' },
      { label: 'Jetzt zahlen', text: 'Im Ticket-Bereich: öffnet den Zahlungsdialog. Erscheint nur, wenn ein Betrag offen ist und die Orga die Zahlungen freigegeben hat.' },
      { label: 'Ticket herunterladen (PNG)', text: 'Speichert dein Ticket als Bilddatei „pakyrion-ticket.png“ auf deinem Gerät.' },
      { label: 'Als PDF', text: 'Öffnet den Druckdialog deines Browsers mit dem Ticket. Dort kannst du „Als PDF speichern“ wählen.' },
      { label: 'Dialog: Zahlung', text: 'Zeigt den zu zahlenden Betrag. „Per PayPal“ und „Per Kreditkarte“ leiten dich zum Zahlungsanbieter weiter. „Per Banküberweisung (automatisch bestätigt)“ geht ebenfalls über den Zahlungsanbieter. „Überweisungsinformationen anzeigen“ zeigt IBAN, BIC, Kontoinhaber und Verwendungszweck für eine normale Überweisung. „Girocode anzeigen“ zeigt einen QR-Code, den du mit der Banking-App scannen kannst. „Schließen“ bricht ab.' },
      { label: 'Logout (Seitenleiste)', text: 'Meldet dich nach einer Rückfrage vom Tool ab und führt zur Anmeldeseite.' },
    ],
  },

  konto: {
    title: 'Konto',
    anchor: 'konto',
    intro: 'Hier pflegst du deine persönlichen Daten, deine Dateien und kannst deine gespeicherten Daten herunterladen.',
    items: [
      { label: 'Vorname / Nachname', text: 'Pflichtfelder (mit * markiert).' },
      { label: 'Rufname', text: 'Optional. Wenn gesetzt, steht dein Rufname z. B. auf dem Ticket statt deines vollen Namens.' },
      { label: 'Discord-Nutzername', text: 'Wird nur angezeigt, wenn dein Konto mit Discord verknüpft ist. Du kannst ihn hier nicht ändern.' },
      { label: 'Weitere Kontofelder', text: 'Felder, die die Orga festlegt (z. B. Kontaktdaten oder Gesundheitshinweise). Ein Schloss-Symbol bedeutet, dass das Feld verschlüsselt gespeichert wird. Allergien und Ähnliches trägst du hier im Konto ein, nicht bei der Anmeldung.' },
      { label: 'Meine Daten für weitere Events speichern', text: 'Freiwilliger Schalter. Ist er an, dürfen deine Daten (Konto und Charaktere) auch nach Ablauf der Löschfristen für weitere Events gespeichert bleiben. Du kannst das jederzeit widerrufen. Der Link führt zur Datenschutzerklärung.' },
      { label: 'Speichern', text: 'Speichert Namen, Kontofelder und den Datenschutz-Schalter. Fehlende Pflichtangaben werden danach im Dashboard nicht mehr angemahnt.' },
      { label: 'Meine Dateien', text: 'Bilder (JPG, PNG, WebP) und PDFs zu deinem Konto, getrennt von den Charakteren.' },
      { label: 'Datei hochladen', text: 'Öffnet die Dateiauswahl, du kannst mehrere Dateien auf einmal wählen. Mit dem Hochladen bestätigst du die Einwilligung, dass berechtigte Personen die Datei einsehen dürfen.' },
      { label: 'Stern (Profilbild festlegen)', text: 'Bei Bildern: macht das Bild zu deinem Profilbild unten links in der Seitenleiste. Erneuter Klick auf den Stern setzt es zurück.' },
      { label: 'Löschen (Datei)', text: 'Löscht die Datei aus deinem Konto, ohne weitere Rückfrage.' },
      { label: 'Meine Daten herunterladen (TXT)', text: 'Lädt eine vollständige Auskunft über alle zu deinem Konto gespeicherten Daten als Textdatei herunter (DSGVO-Auskunft).' },
      { label: 'Hochgeladene Dateien herunterladen (ZIP)', text: 'Lädt alle von dir hochgeladenen Dateien als ZIP herunter. Sind keine vorhanden, bekommst du eine Meldung.' },
    ],
  },

  anmelden: {
    title: 'Anmelden',
    anchor: 'anmelden',
    intro: 'Hier meldest du dich für ein Event an, änderst deine Anmeldung, wählst die Unterkunft und kannst dich wieder abmelden.',
    items: [
      { label: 'Meine Anmeldungen', text: 'Überschrift der Anmeldungsansicht. Rechts siehst du die Karte deiner aktuellen Anmeldung (siehe unten).' },
      { label: 'Du bist angemeldet', text: 'Ersetzt das Anmeldeformular, sobald du für alle offenen Events angemeldet bist. Hast du dich abgemeldet, steht dort der Hinweis, dich an die Orga zu wenden, falls du doch teilnehmen willst.' },
      { label: 'Neu anmelden', text: 'Das Anmeldeformular. Es erscheint nur, solange es ein offenes Event gibt, für das du noch nicht angemeldet bist. Der Hinweis oben erinnert dich, Allergien und Ähnliches im Tab „Konto“ zu pflegen.' },
      { label: '1. Veranstaltung & Teilnahme: Event', text: 'Normale Teilnehmer sehen hier nur das eine geöffnete Event als Text. Nur Mitarbeitende mit entsprechenden Rechten haben ein Auswahlfeld und sehen auch nicht geöffnete Events.' },
      { label: 'Offene Registrierung / Registrierung geschlossen', text: 'Zeigt, ob das Event aktuell Anmeldungen annimmt.' },
      { label: 'Nur noch wenige Plätze verfügbar', text: 'Hinweis-Markierung, die nur erscheint, wenn das Event fast voll ist.' },
      { label: 'Als Spielercharakter (SC)', text: 'Du spielst deinen eigenen Charakter. Du musst dafür einen Charakter wählen.' },
      { label: 'Als Nichtspieler (NSC)', text: 'Du unterstützt die Spielleitung, entweder mit fester Rolle oder flexibel als Springer.' },
      { label: '2. Deine Rolle: Als welcher Charakter kommst du?', text: 'Nur bei SC. Auswahl deiner Charaktere. Charaktere, die schon für ein Event angemeldet sind, stehen ausgegraut in der Liste.' },
      { label: 'Charakter anlegen (bei SC)', text: 'Erscheint, wenn du noch keinen Charakter hast. Führt zum Tab „Charaktere“.' },
      { label: 'Hast du eine feste Rolle? (NSC)', text: 'Nur bei NSC. Wähle einen Charakter, wenn du eine feste Figur spielst, sonst lässt du „Kein Charakter – ich komme als Springer“ stehen.' },
      { label: 'Neuen Charakter anlegen (bei NSC)', text: 'Führt zum Tab „Charaktere“, um eine Figur für den NSC-Einsatz anzulegen.' },
      { label: 'NSC-Fragebogen', text: 'Erscheint bei NSC unter der Charakterauswahl. Die Felder legt die Orga fest; sie dienen der Spielleitung zur Einplanung.' },
      { label: 'Teilnahmegruppe', text: 'Erscheint nur, wenn das Event Teilnahmegruppen hat. Danach richtet sich der Preis deines Tickets. Hat die Orga Regeln hinterlegt, wird eine passende Gruppe vorgewählt (das siehst du am Hinweis „Vorgewählt“); du kannst sie ändern. Darunter steht die Preistabelle der gewählten Gruppe.' },
      { label: 'Zubuchbare Extras', text: 'Erscheint nur, wenn das Event Extras anbietet (z. B. Hütte oder Stellplatz). Du wählst, was du dazubuchen möchtest; die Summe wird mitgerechnet.' },
      { label: 'Unterbringung mieten', text: 'Erscheint nur, wenn die Orga das Zusatzmodul „Unterkünfte“ aktiviert hat und das Event Unterkünfte hat. Du wählst eine Unterkunft bzw. ein Bett. Setzt du das Häkchen, musst du auch eine Unterkunft wählen.' },
      { label: 'Sonderrollen', text: 'Erscheint nur, wenn das Event Sonderrollen definiert hat. Optional: Wähle aus, was auf dich zutrifft.' },
      { label: '3. Weitere Angaben zu dieser Anmeldung', text: 'Felder, die die Orga für die Anmeldung festlegt.' },
      { label: 'Erinnerung vor Fristablauf', text: 'Wenn angehakt, bekommst du eine Woche vor jedem Fristablauf der Preisstufen eine E-Mail. Jede Mail enthält einen Link zum Abbestellen.' },
      { label: '4. AGB & Einverständniserklärung', text: 'Erscheint nur, wenn die Orga einen Text hinterlegt hat. Das Häkchen ist dann Pflicht, sonst kannst du dich nicht anmelden.' },
      { label: 'Anmelden / Anmelden für {Event}', text: 'Schickt deine Anmeldung ab. Sie ist verbindlich, kann danach aber in der Karte rechts bearbeitet werden. Nach dem Absenden kommst du zu einer Bestätigungsseite.' },
      { label: 'Anmeldungs-Karte (rechts)', text: 'Zeigt dein Event, als wen du angemeldet bist, gebuchte Extras, Unterkunft, Status und die Preistabelle mit deiner Teilnahmegruppe. „auch NSC-bereit“ erscheint, wenn du dich zusätzlich als NSC zur Verfügung stellst. Bist du noch nicht angemeldet, steht dort stattdessen ein Hinweis mit dem Button „Jetzt anmelden“, der ins Formular springt.' },
      { label: 'Bearbeiten', text: 'Öffnet den Dialog „Anmeldungsdaten bearbeiten“.' },
      { label: 'Dialog: Anmeldungsdaten bearbeiten', text: 'Hier änderst du Sonderrollen, Extras und die Anmeldungsfelder. Speichern benachrichtigt die Orga und Admins des Events per E-Mail, aber nur, wenn du wirklich etwas geändert hast. Extras sind gesperrt, sobald die Anmeldung bezahlt oder abgesagt ist. „Abbrechen“ verwirft die Änderungen.' },
      { label: 'Unterkunft wählen / Unterkunft ändern', text: 'Erscheint nur, wenn das Zusatzmodul „Unterkünfte“ aktiv ist, das Event Unterkünfte hat und deine Anmeldung nicht abgesagt oder auf der Warteliste ist. Öffnet den Unterkunft-Dialog.' },
      { label: 'Dialog: Unterkunft', text: 'Wähle ein Bett, dann siehst du, wer mit dir in der Unterkunft schläft. „Speichern“ übernimmt die Wahl, „Abbrechen“ schließt ohne Änderung.' },
      { label: 'Abmelden', text: 'Erscheint, solange deine Anmeldung offen, auf der Warteliste oder bestätigt ist. Nach einer Rückfrage wirst du abgemeldet. Ist die Anmeldung schon bestätigt, prüft die Orga die Abmeldung manuell, auch eine mögliche Erstattung der Ticketgebühr.' },
      { label: 'Status (offen, Warteliste, bestätigt, abgesagt)', text: 'Die farbige Markierung zeigt den Stand deiner Anmeldung. Als Con-Zahler wird das entsprechend angezeigt.' },
      { label: 'NSC-Dialog', text: 'Karte erscheint nur, wenn du als NSC angemeldet oder NSC-bereit bist. Du schreibst hier der Orga, was du als NSC spielen möchtest. Nur die Orga liest mit.' },
      { label: 'Annehmen / Ablehnen (Rollenvorschlag)', text: 'Macht dir die Orga einen Rollenvorschlag, entscheidest du hier. Die Antwort ist danach für die Orga sichtbar und der Vorschlag zeigt „angenommen“ oder „abgelehnt“.' },
      { label: 'Nachricht an die Orga / Senden', text: 'Schickt deine Nachricht (bis 2000 Zeichen) an die Orga. Sie erscheint im Verlauf darüber.' },
    ],
  },

  gruppe: {
    title: 'Gruppe',
    anchor: 'gruppe',
    intro: 'Hier verwaltest du deine Gruppe: Personen anlegen, Mitglieder einladen, alle gemeinsam anmelden und Gruppenangaben pflegen.',
    items: [
      { label: 'Menüpunkt „Gruppe“', text: 'Erscheint in der Seitenleiste, sobald du den Schalter auf dem Dashboard einschaltest, Personen verwaltest oder zu einer Gruppe gehörst.' },
      { label: 'Nur Mitglied einer fremden Gruppe', text: 'Bist du nur eingeladenes Mitglied, siehst du hier ohne Reiter nur, wer in der Gruppe ist, und kannst die Gruppe verlassen.' },
      { label: 'Reiter „Gruppe“', text: 'Zeigt alle Personen deiner Gruppe als Karten: von dir angelegte Personen („Angelegt“) und eingeladene Verwalter mit ihren Personen („Eingeladen“).' },
      { label: 'Ganze Gruppe anmelden', text: 'Öffnet den Dialog zum gemeinsamen Anmelden. Funktioniert nur, wenn gerade ein Event für Anmeldungen offen ist.' },
      { label: 'Dialog: Ganze Gruppe anmelden', text: 'Wähle das Event und hake die Personen an. Für jede Person wählst du den Spielercharakter (oder „Charakter folgt später“). Teilnahmegruppe, Zusatzfelder und Unterkunft ergänzt du danach bei der Person. Bereits angemeldete Personen sind markiert. Gibt es einen AGB-Text, musst du für alle gemeinsam zustimmen. Nach „Anmelden“ siehst du je Person Erfolg oder Fehler samt Link zur Einzelanmeldung. „Schließen“ beendet den Dialog.' },
      { label: 'Charaktere & Anmeldung verwalten', text: 'Auf der Karte einer von dir angelegten Person: öffnet die eigene Seite der Person, wo du ihre Charaktere und Anmeldung bearbeitest.' },
      { label: 'Bearbeiten (Person)', text: 'Öffnet den Dialog zum Bearbeiten von Vorname, Nachname, Rufname, E-Mail und den weiteren Feldern der Person.' },
      { label: 'Aus Gruppe entfernen', text: 'Nach einer Rückfrage wird die Person aus deiner Gruppe entfernt. Sie wird nicht gelöscht, du kannst sie aber nicht mehr verwalten.' },
      { label: 'Einladungslink erzeugen', text: 'Erzeugt einen Link, mit dem die Person ein eigenes Konto anlegt. Hat sie eine E-Mail hinterlegt, bekommt sie den Link auch per Mail. Der Link wird dir angezeigt und in die Zwischenablage kopiert. Nach dem Einlösen hast du keinen Zugriff mehr auf ihre Daten.' },
      { label: 'Anmelden / Anmeldungen (eingeladenes Mitglied)', text: 'Auf der Karte eines eingeladenen Mitglieds oder seiner Personen: öffnet die Seite zum Anmelden bzw. zur Anmeldeübersicht.' },
      { label: 'Gruppen-Felder', text: 'Öffnet den Dialog, in dem du die für die Gruppenverwaltung freigegebenen Konto-, Charakter- und NSC-Felder dieser Person bearbeitest. Jeder Block hat ein eigenes „Speichern“. Die Person sieht Änderungen auf ihrem Dashboard und kann sie dort prüfen.' },
      { label: 'Entfernen (Mitglied)', text: 'Nach einer Rückfrage wird das eingeladene Mitglied aus deiner Gruppe entfernt. Nur bei direkten Mitgliedern möglich.' },
      { label: 'Gruppe verlassen', text: 'Erscheint, wenn du zur Gruppe einer anderen Person gehörst. Nach Rückfrage trittst du aus.' },
      { label: 'Reiter „Gruppeneinstellungen“', text: 'Name und Angaben deiner Gruppe. Der Name erscheint in der Gruppenstruktur und in Einladungen.' },
      { label: 'Gruppenname', text: 'Freier Name für deine Gruppe, maximal 60 Zeichen.' },
      { label: 'Weitere Gruppenfelder', text: 'Felder, die die Orga für Gruppen festlegt. Sie erscheinen nur, wenn welche definiert sind.' },
      { label: 'Speichern (Gruppeneinstellungen)', text: 'Speichert Gruppenname und Gruppenfelder zusammen.' },
      { label: 'Reiter „Leute einladen“', text: 'Sammelt alle Wege, Personen in deine Gruppe zu holen.' },
      { label: 'Neue Person anlegen', text: 'Für Personen ohne eigenen Login (Familie, Kinder, Freunde, die du selbst verwaltest). Öffnet den Dialog „Person hinzufügen“.' },
      { label: 'Dialog: Person hinzufügen', text: 'Zwei Wege: „Person anlegen“ (Name, E-Mail optional) oder „Charakter anlegen“ (legt einen Spielercharakter samt Person dahinter an). Alles Weitere kannst du später ergänzen. „Abbrechen“ schließt ohne Anlegen.' },
      { label: 'Dialog: Person bearbeiten', text: 'Gleicher Dialog beim Bearbeiten: Vorname, Nachname, Rufname, E-Mail (optional, nötig für eine spätere Umwandlung in ein eigenes Konto) und weitere Felder. Du siehst nur Felder, die du selbst setzen darfst. „Speichern“ übernimmt, „Abbrechen“ verwirft.' },
      { label: 'Suchen (Vorhandene Person oder Account)', text: 'Öffnet den Suchdialog.' },
      { label: 'Dialog: Vorhandene Person in die Gruppe holen', text: 'Suche mit mindestens 3 Zeichen nach Name, Charaktername oder E-Mail. Personen ohne Login holst du direkt in die Gruppe („In meine Gruppe holen“). Accounts mit Login lädst du ein („In meine Gruppe einladen“); sie gehören erst zu deiner Gruppe, wenn sie zustimmen.' },
      { label: 'Vollständige E-Mail-Adresse / Einladung senden', text: 'Lädt einen Gruppenverwalter per E-Mail ein. Hat die Person schon ein Konto, erscheint die Einladung dort im Dashboard. Sonst bekommt sie einen Link zum Anmelden und kommt direkt in die Gruppe. Die offene Einladung steht danach unter „Offene Einladungen“.' },
      { label: 'Code einlösen', text: 'Nur sichtbar und möglich, solange du in keiner Gruppe bist und selbst keine verwaltest. Mit dem Code eines Gruppenverwalters trittst du dessen Gruppe bei.' },
      { label: 'Code erzeugen (Beitrittscodes)', text: 'Erstellt einen Beitrittscode mit Gültigkeit (1 Tag bis unbegrenzt) und erlaubter Anzahl Einlösungen (oder unbegrenzt). Der Code wird nur einmal angezeigt, gib ihn gleich weiter. Wer ihn einlöst und noch in keiner Gruppe ist, kommt direkt in deine Gruppe.' },
      { label: 'Liste der Codes / Löschen', text: 'Zeigt deine Codes mit den letzten Zeichen, Restanzahl und Ablauf. „Löschen“ macht einen Code nach Rückfrage unbenutzbar.' },
      { label: 'Offene Einladungen / Zurückziehen', text: 'Zeigt deine noch nicht beantworteten Einladungen. „Zurückziehen“ nimmt eine Einladung zurück.' },
    ],
  },

  charaktere: {
    title: 'Charaktere',
    anchor: 'charaktere',
    intro: 'Hier legst du deine Spielercharaktere an, bearbeitest sie, verwaltest ihre Bilder und Dokumente und löschst sie.',
    items: [
      { label: 'Charaktere anderer Spieler durchsuchen', text: 'Link zur Charakter-Suche. Er erscheint nur, wenn die Orga das Durchsuchen freigeschaltet hat.' },
      { label: 'Neuen Charakter anlegen', text: 'Öffnet das leere Formular für einen neuen Charakter.' },
      { label: 'Aus bestehendem Charakter kopieren', text: 'Erscheint nur, wenn du schon einen Charakter hast. Öffnet den Kopier-Dialog.' },
      { label: 'Dialog: Charakter kopieren', text: 'Wähle eine Vorlage. Name und Sheet-Daten werden in ein neues Formular übernommen. Der neue Charakter ist unabhängig vom alten und wird erst mit „Speichern“ angelegt.' },
      { label: 'Charakterkarten', text: 'Jeder Charakter ist eine Karte mit Bild und Name. Ein Klick öffnet ihn zum Bearbeiten, die Karte ist dann markiert.' },
      { label: 'Foto-Symbol (Kamera)', text: 'Auf der Karte: lädt ein Foto hoch.' },
      { label: 'Dialog: Foto hochladen', text: 'Wähle ein Bild (JPG, PNG oder WebP). Mit dem Hochladen bestätigst du, dass du die Rechte am Bild hast und dass berechtigte Personen es im Rahmen der Veranstaltung ansehen dürfen.' },
      { label: 'X-Symbol auf der Karte', text: 'Öffnet den Dialog zum Löschen des Charakters.' },
      { label: 'Dialog: Charakter löschen', text: 'Nicht rückgängig zu machen. Zur Bestätigung gibst du den Namen des Charakters ein. Ist der Charakter für ein Event angemeldet, erscheint eine Warnung: Die Teilnahme entfällt, die Orga wird benachrichtigt und klärt eine mögliche Stornierung und Erstattung. Erst mit „Trotzdem löschen“ wird gelöscht.' },
      { label: 'Charakter-Formular: 1. Charaktername', text: 'Pflichtfeld.' },
      { label: 'Charakter-Formular: 2. Charakterdaten', text: 'Felder, die die Orga für Charaktere festlegt. Manche Felder sind nur für Mitarbeitende bearbeitbar und für dich schreibgeschützt.' },
      { label: 'Speichern / Änderungen speichern', text: 'Legt den Charakter an bzw. speichert Änderungen. Nach dem Anlegen öffnet sich der neue Charakter gleich im Bearbeitungsmodus, damit du Bilder ergänzen kannst.' },
      { label: 'Abbrechen (Charakter-Formular)', text: 'Schließt das Formular und verwirft ungespeicherte Eingaben samt vorgemerkter Dateien.' },
      { label: 'Bilder & Dokumente', text: 'Rechte Spalte: Dateien des gewählten Charakters. Du kannst Dateien über „Dateien auswählen“ wählen oder hineinziehen (JPG, PNG, WebP und PDF). Bei einem neuen, noch ungespeicherten Charakter werden sie nur vorgemerkt und beim Speichern hochgeladen.' },
      { label: 'Stern (Charakterportrait)', text: 'Bei Bildern: macht das Bild zum Portrait, das auf Karten und im Dashboard angezeigt wird. Erneuter Klick setzt es zurück. Ohne Portrait wird das erste Bild verwendet.' },
      { label: 'Löschen / X bei Datei', text: 'Löscht die Datei nach einer Rückfrage. Bei vorgemerkten Dateien entfernt „Entfernen“ sie nur aus der Vormerkung.' },
    ],
  },
};
