// Hilfetexte der Admin-Seiten (Charakterschema, E-Mail, Abgleich, Einstellungen, PDF, Unterkünfte).
export default {
  '/admin/character-schema.html': {
    title: 'Charakterschema',
    anchor: 'schema',
    intro: 'Hier legst Du fest, welche Felder Charaktere, Konten, Anmeldungen und Gruppen haben. Die Schemas gelten app-weit für alle Events.',
    items: [
      { label: 'Tab „SC/GSC“', text: 'Felder für Spielercharaktere (SC/GSC). Alle SC/GSC-Charaktere teilen sich dieses Schema über alle Events hinweg.' },
      { label: 'Tab „NSC“', text: 'Eigenes Schema für Nichtspielercharaktere, ebenfalls mit Gruppen-Überschriften.' },
      { label: 'Tab „Konto“', text: 'OT-Felder (Out-Time), die jede Person einmal in ihrem Konto ausfüllt, z. B. Adresse oder Gesundheitshinweise.' },
      { label: 'Tab „Anmeldung“', text: 'OT-Felder, die bei jeder Event-Anmeldung abgefragt werden und nur für diese Anmeldung gelten.' },
      { label: 'Tab „Gruppe“', text: 'Felder, die Gruppenverwalter unter „Gruppe → Gruppeneinstellungen“ für ihre Gruppe ausfüllen. Hier gibt es nur die Grundoptionen.' },
      { label: 'Feld hinzufügen', text: 'Fügt am Ende der Liste eine leere Zeile hinzu. Erst mit „Speichern“ wird sie übernommen.' },
      { label: 'Standard-Vorlage laden', text: 'Nur im Tab SC/GSC: Ersetzt alle aktuellen Zeilen durch das mitgelieferte Standard-Schema. Gespeichert wird erst nach Klick auf „Speichern“.' },
      { label: 'Speichern', text: 'Speichert das Schema des gerade offenen Tabs. Zeilen ohne key werden verworfen. Die anderen Tabs werden nicht mitgespeichert.' },
      { label: '▲ / ▼', text: 'Verschiebt das Feld nach oben oder unten. Die Reihenfolge ist die Reihenfolge in den Formularen.' },
      { label: 'key', text: 'Interner Name des Feldes, unter dem die Antworten gespeichert werden. Ändere ihn nicht nachträglich, sonst gelten alte Antworten als anderes Feld. Der key „medicalNotes“ (Gesundheitsdaten) ist immer sensibel.' },
      { label: 'Label', text: 'Die Beschriftung, die Nutzer im Formular sehen.' },
      { label: 'Gruppe (z. B. Grunddaten)', text: 'Nur bei SC/GSC und NSC: Felder mit gleichem Gruppennamen werden im Formular unter einer gemeinsamen Überschrift zusammengefasst. Leer = Sammelgruppe.' },
      { label: 'Feldtyp', text: 'Text, Textarea (mehrzeilig), Dokument (Editor mit Formatierung), Auswahl (eine Option), Zahl, Ja/Nein, Mehrfachauswahl, Link oder Datum.' },
      { label: 'Optionen', text: 'Nur bei Auswahl und Mehrfachauswahl: die möglichen Antworten, getrennt mit |, z. B. „Ja | Nein | Vielleicht“.' },
      { label: 'Pflichtfeld', text: 'Das Feld muss ausgefüllt sein, sonst lässt sich das Formular nicht speichern.' },
      { label: 'Öffentlich sichtbar', text: 'Nur bei den Charakter-Tabs: Das Feld ist für andere Spieler sichtbar (z. B. in „Charaktere durchsuchen“, wenn aktiviert).' },
      { label: 'Nur Staff darf bearbeiten', text: 'Nur bei den Charakter-Tabs: Spieler sehen das Feld, können es aber nicht ändern. Nur Orga/Staff kann es bearbeiten.' },
      { label: 'Gruppenverwaltung', text: 'Bei Charakter-, Konto- und Anmelde-Feldern: Der übergeordnete Gruppenverwalter darf dieses Feld bei den Mitgliedern seiner Untergruppen bearbeiten.' },
      { label: 'Als Card darstellen', text: 'Das Feld wird im Formular als eigene Karte (Card) hervorgehoben dargestellt.' },
      { label: 'Beim Check-in abfragen', text: 'Beim Einchecken wird dieses Feld der Person noch einmal gezeigt und kann dort korrigiert werden.' },
      { label: 'Sensibel', text: 'Nur bei Konto und Anmeldung: Das Feld fehlt in CSV-Exporten, außer die exportierende Gruppe hat das Recht „sensible Felder exportieren“.' },
      { label: 'Platzhalter im Eingabefeld', text: 'Optionaler grauer Beispieltext im leeren Eingabefeld, höchstens 120 Zeichen.' },
      { label: 'Hinweis beim Darüberfahren', text: 'Optionaler Erklärungstext, der beim Überfahren des Feldes erscheint, höchstens 500 Zeichen.' },
      { label: 'Entfernen', text: 'Löscht die Zeile aus der Liste. Erst mit „Speichern“ wird das Feld wirklich aus dem Schema entfernt.' },
    ],
  },

  '/admin/email-templates.html': {
    title: 'E-Mail-Vorlagen',
    anchor: 'email',
    intro: 'Hier erstellst Du Vorlagen für E-Mails und legst fest, welche Vorlage für welche automatische System-E-Mail verwendet wird.',
    items: [
      { label: 'System-E-Mails', text: 'Pro automatischem Mailtyp (z. B. E-Mail-Verifizierung, Passwort zurücksetzen, Einladung, Warteliste, Zahlungserinnerung, Event abgesagt, Orga-Hinweise) wählst Du eine eigene Vorlage. Die Auswahl wird sofort gespeichert.' },
      { label: 'Standardtext (System)', text: 'Ist keine Vorlage gewählt, wird der eingebaute Standardtext verschickt.' },
      { label: 'Variablen je Mailtyp', text: 'Unter dem Mailtyp stehen die zusätzlichen Variablen, die in dieser Mail verfügbar sind, z. B. {{link}} oder {{eventName}}. Diese gibst Du von Hand in Betreff oder Inhalt ein.' },
      { label: 'Vorlagenliste', text: 'Zeigt Name, Betreff und Format (HTML oder Klartext) aller Vorlagen.' },
      { label: 'Bearbeiten', text: 'Lädt die Vorlage ins Formular darunter und blendet den Bereich „Vorschau & Testmail“ ein.' },
      { label: 'Löschen', text: 'Löscht die Vorlage nach Rückfrage.' },
      { label: 'Name', text: 'Nur intern zur Unterscheidung, erscheint nicht in der Mail.' },
      { label: 'Betreff', text: 'Betreffzeile der Mail. Platzhalter sind erlaubt.' },
      { label: 'Inhalt', text: 'Text der Mail. Platzhalter wie {{account.feldkey}} werden beim Versand durch die Daten des Empfängers ersetzt.' },
      { label: 'Als HTML senden', text: 'Aktiviert: Der Inhalt wird als HTML-Mail gesendet. Aus: Klartext.' },
      { label: 'Felder einfügen (OT-Felder)', text: 'Ein Klick fügt einen Platzhalter für ein Konto-Feld an der Cursorposition ein. Verwendet wird das zuletzt angeklickte Feld von Betreff oder Inhalt.' },
      { label: 'Felder einfügen (IT-Felder)', text: 'Wie oben, aber für Charakter-Felder (Platzhalter {{character.feldkey}}).' },
      { label: 'Abbrechen', text: 'Verwirft die Bearbeitung und leert das Formular.' },
      { label: 'Speichern / Änderungen speichern', text: 'Legt die Vorlage an bzw. speichert Änderungen. Danach bleibt sie zur Bearbeitung geöffnet.' },
      { label: 'Vorschau & Testmail: Mitglied / Charakter', text: 'Nur bei einer gespeicherten Vorlage. Wähle ein Mitglied (nur mit E-Mail, keine offenen Einladungen) und optional einen seiner Charaktere, dessen echte Daten eingesetzt werden.' },
      { label: 'Vorschau anzeigen', text: 'Zeigt Betreff und Inhalt mit den eingesetzten Daten, ohne etwas zu senden. Nutzt die gespeicherte Fassung der Vorlage, speichere also vorher.' },
      { label: 'Testmail senden', text: 'Sendet die Vorlage wirklich an die E-Mail-Adresse des gewählten Mitglieds. Das setzt einen funktionierenden SMTP-Zugang voraus.' },
    ],
  },

  '/admin/sync.html': {
    title: 'Datenabgleich',
    anchor: 'sync',
    intro: 'Hier steuerst Du die Übergabe von Check-in und Taverne an eine Offline-Instanz vor Ort, die Rückgabe der Daten und die Klärung von Konflikten.',
    items: [
      { label: 'Hinweisbanner „Offline-Version aktiv“', text: 'Erscheint online, solange ein Event an die Offline-Version delegiert ist. Check-in und Taverne sind dann online gesperrt, bis die Rückgabe erfolgt ist.' },
      { label: 'Notfall-Freigabe', text: 'Im Banner: Gibt das Schreibrecht online sofort zurück, auch bei offenen Konflikten. Nach zwei Rückfragen, wird protokolliert. Offline erfasste Buchungen und Check-ins, die nicht zurückgegeben wurden, gehen verloren oder werden später nur als Konflikt angeboten.' },
      { label: 'Status', text: 'Zeigt, ob Du auf der Online- oder der Offline-Instanz bist, und die Zahl offener Konflikte.' },
      { label: 'Status-Tabelle', text: 'Pro Event: Zustand (Delegiert, Offline schreibberechtigt, Offline beendet), Stand des Snapshots, wer wann delegiert hat und die Generation. Ohne Eintrag sind alle Events normal online schreibberechtigt.' },
      { label: 'Delegation aufheben', text: 'Nur online bei delegierten Events. Gibt das Schreibrecht an Online zurück. Geht nur ohne offene Konflikte, sonst Konflikte zuerst lösen oder die Notfall-Freigabe nutzen. Zwei Rückfragen, nicht rückgängig zu machen.' },
      { label: 'Rückgabe einspielen: Rückgabedatei', text: 'Nur online sichtbar. Lade die .qpkg-Datei hoch, die die Offline-Instanz beim Export erzeugt hat.' },
      { label: 'Rückgabe einspielen: Passphrase', text: 'Die Passphrase, die beim Export vergeben wurde (mindestens 8 Zeichen).' },
      { label: 'Zwischenabgleich (Online bleibt delegiert)', text: 'Spielt die Daten ein, lässt aber die Delegation bestehen. Offline arbeitet also weiter, online bleibt gesperrt.' },
      { label: 'Einspielen', text: 'Startet den Import. Das Ergebnis steht darunter. Offline eingegangene Änderungen, die online anders geändert wurden, werden als Konflikte angelegt.' },
      { label: 'Konflikte: Filter Status', text: 'Zeigt offene oder gelöste Konflikte.' },
      { label: 'Konflikte: Filter Typ', text: 'Beschränkt die Liste auf eine Art, z. B. Anmeldung online geändert, Konto online gelöscht, Kontonummer doppelt, Saldo stimmt nicht, Doppelter Walk-in, Delegation aufgehoben, Unbekannter Datensatz, Uhrenabweichung.' },
      { label: 'CSV-Export', text: 'Lädt die Konfliktliste des gewählten Status als CSV herunter.' },
      { label: 'Konfliktkarte', text: 'Stellt Offline-Stand und Online-Stand nebeneinander dar. Abweichende Werte sind markiert.' },
      { label: 'Notiz (optional)', text: 'Freitext, der beim Lösen des Konflikts mitgespeichert wird.' },
      { label: 'Offline übernehmen / Online behalten / Zusammenführen / Ignorieren', text: 'Lösungsarten, nur online und nur bei offenen Konflikten. Welche angeboten werden, hängt vom Konflikttyp ab. Sind alle Konflikte gelöst, bekommt Online automatisch wieder das Schreibrecht.' },
      { label: 'Nur-Lese-Hinweis (Offline-Instanz)', text: 'Auf der Offline-Instanz wird die Konfliktliste nur angezeigt. Gelöst wird online.' },
    ],
  },

  '/admin/settings.html': {
    title: 'Einstellungen',
    anchor: 'einstellungen',
    intro: 'Hier stellst Du allgemeine Optionen, E-Mail, Zahlungen, Startseite, Aussehen, Datei-Speicher und Zusatzmodule ein. Der offene Tab steht in der Adresse (z. B. #email).',
    items: [
      { label: 'Anzeige „Nicht gespeichert / Gespeichert ✓“', text: 'Neben dem Speichern-Button jedes Formulars. Beim Verlassen der Seite mit ungespeicherten Änderungen warnt der Browser. Schalter speichern dagegen sofort.' },

      { label: 'Tab „Allgemein“', text: 'Basis-URL, Einladungen, Zahlungserinnerungen, Warteliste, Charakter-Suche sowie AGB und Rechtstexte.' },
      { label: 'Basis-URL', text: 'Grundlage für Links in E-Mails (Bestätigung, Passwort-Reset, Einladungen, Zahlung). Leer = Umgebungsvariable APP_BASE_URL des Servers. Darunter steht, welche URL aktuell aktiv ist. Eine falsche URL führt zu kaputten Links in Mails.' },
      { label: 'Einladungen: Gültig für (Tage)', text: 'Wie lange ein Einladungslink gültig bleibt. Danach läuft er ab.' },
      { label: 'Zahlungserinnerungen an die Orga', text: 'Per PDF angemeldete Personen bleiben offen, bis sie zahlen. Nach 1, 2 und 3 eingetragenen Tagen (1 bis 365) bekommt die Orga je eine Mail mit der Liste der offenen Zahlungen. Leer = keine Erinnerung. Con-Zahler zählen nicht.' },
      { label: 'Teilnehmerlimit: welche Rollen zählen mit?', text: 'Nur angehakte Rollen zählen gegen die Teilnehmergrenzen eines Events (Gesamt, SC, NSC). Standard: SC, NSC und Direktanmeldungen zählen, Helfer, Hilfs-Orga und Orga nicht. Nicht zählende Rollen können sich immer anmelden und nehmen keinen Platz weg. Beim Speichern rücken Wartende nach, wo jetzt Platz ist.' },
      { label: 'Warteliste: Automatisch nachrücken lassen', text: 'An: Wird ein Platz frei, rückt die am längsten wartende Person automatisch nach. Aus: Staff muss im Check-In-Bereich manuell nachrücken lassen. Wirkt sofort.' },
      { label: 'Charaktere durchsuchen aktiviert', text: 'Schaltet die Seite „Charaktere anderer Spieler durchsuchen“ für alle Nutzer ein oder aus. Wirkt sofort.' },
      { label: 'AGB & Einverständniserklärung', text: 'Text, dem Teilnehmer bei der Event-Anmeldung per Pflicht-Häkchen zustimmen müssen (einfaches HTML erlaubt). Leer = keine Zustimmung nötig. Jede Textänderung erhöht automatisch die Version, damit nachvollziehbar bleibt, welcher Fassung jemand zugestimmt hat.' },
      { label: 'Datenschutzerklärung & Impressum', text: 'Je Dokument: „Nicht konfiguriert“ (Datenschutz zeigt die eingebaute Erklärung, das Impressum wird nicht verlinkt), „Link auf externe Seite“ oder „Eigener Text“ (mit Editor). Die Links erscheinen unten auf öffentlichen Seiten und in der Seitenleiste.' },

      { label: 'Tab „Check-In“: Hotkeys', text: 'Klicke in ein Feld und drücke die gewünschte Taste für „Einchecken (im Pop-up)“, „Abbrechen (im Pop-up)“ und „Scan starten (Push-to-See)“. Die Taste wird sofort in Deinem Konto gespeichert. Vom Browser reservierte oder doppelt belegte Tasten werden abgelehnt.' },

      { label: 'Tab „E-Mail“: SMTP-Zugang', text: 'Host, Port, Benutzername, Passwort und Absender-Adresse für den Versand von Registrierung, Passwort-Reset und Einladungen. Ein leeres Passwort-Feld behält das gespeicherte Passwort. Ohne gültigen Zugang kommen keine Mails an.' },
      { label: 'Test-Mail senden', text: 'Schickt eine Testmail an die Ziel-E-Mail-Adresse mit den aktuell eingetragenen Feldern, ohne sie zu speichern. So prüfst Du Zugangsdaten vor dem Speichern.' },

      { label: 'Tab „Zahlungen“, Karte „Stripe“: Stripe Secret Key', text: 'Zugangsschlüssel für Stripe, das Kreditkarte, PayPal und automatisch bestätigte Banküberweisung verarbeitet. Leer lassen behält den gespeicherten Schlüssel.' },
      { label: 'Stripe Webhook Signing Secret', text: 'Prüfschlüssel, mit dem Zahlungsbestätigungen von Stripe als echt erkannt werden. Leer lassen behält das gespeicherte Secret.' },
      { label: 'Schalter „… anbieten (live schalten)“ (in jeder Zahlungs-Karte)', text: 'Jede Zahlungsart hat einen eigenen Schalter. Du kannst Zugangsdaten schon vorab speichern, die Zahlungsart erscheint für Teilnehmende aber erst, wenn der Schalter an ist und die Daten vollständig sind. Ausschalten nimmt sie wieder aus dem Angebot; bereits laufende Zahlungen werden trotzdem noch verbucht. Beim Aktualisieren der App bleiben bereits eingerichtete Zahlungsarten an.' },
      { label: 'Karte „PayPal (privates Konto)“: PayPal.Me-Link', text: 'Für ein privates PayPal-Konto ohne Händler-Zugang. Teilnehmende zahlen über deinen Link (https://paypal.me/DeinName), der Betrag ist schon eingetragen. PayPal meldet die Zahlung nicht zurück: Du siehst sie in deinem PayPal-Konto und bestätigst sie selbst im Check-In. Teilnehmende klicken nach der Zahlung auf „Ich habe bezahlt“, dann erscheint die Meldung wie bei Überweisungen.' },
      { label: 'Karte „Stripe“: Zahlungsarten', text: 'Mit den Kästchen legst du fest, welche Stripe-Zahlungsarten Teilnehmende sehen: Kreditkarte (inkl. Apple Pay und Google Pay), PayPal, Banküberweisung, Klarna und SEPA-Lastschrift. Jede Art muss auch in deinem Stripe-Dashboard aktiviert sein. Lastschrift und Banküberweisung werden erst bestätigt, wenn das Geld eingetroffen ist.' },
      { label: 'Karte „PayPal“: Client-ID / Secret / Sandbox', text: 'Zahlung direkt über PayPal, unabhängig von Stripe. Die Person bezahlt bei PayPal und kommt zurück zur App; die Zahlung wird dann automatisch geprüft und als bezahlt gebucht. Client-ID und Secret erzeugst du im PayPal-Entwicklerportal unter „Apps & Credentials“. Das Secret wird verschlüsselt gespeichert und nie wieder angezeigt. „Sandbox“ ist der Testmodus ohne echtes Geld. Erstattungen machst du im PayPal-Konto und trägst sie im Check-In ein.' },
      { label: 'PayPal-Buttons zusätzlich auf unserer Seite zeigen', text: 'Zeigt im Zahlungsfenster zusätzlich PayPals eigene Bezahl-Buttons (PayPal, Lastschrift, Karte). Dafür lädt die Seite ein Skript von PayPal. Die Buttons ersetzen den Eintrag „Per PayPal zahlen“ (Weiterleitung). Lässt sich das Skript einmal nicht laden, erscheint die Weiterleitung automatisch wieder. Die Client-ID wird dabei im Browser sichtbar, das ist bei PayPal so vorgesehen; das Secret bleibt auf dem Server. Der Betrag kommt immer vom Server.' },
      { label: 'Karte „SumUp“: API-Schlüssel / Merchant-Code', text: 'Zugangsdaten für Zahlungen über SumUp. Teilnehmende sehen dann im Zahlungsdialog „Per SumUp“ und zahlen auf der SumUp-Seite (Karte, Apple Pay, Google Pay). Die Zahlung wird automatisch bestätigt. Der Schlüssel wird verschlüsselt gespeichert und nie wieder angezeigt; leer lassen behält ihn. Erstattungen machst du im SumUp-Dashboard und trägst sie im Check-In ein.' },
      { label: 'Karte „Manuelle Banküberweisung“: IBAN / BIC / Kontoinhaber', text: 'Kontodaten, die Teilnehmern bei der manuellen Überweisung angezeigt werden. Die Zahlung bestätigst du selbst im Check-In.' },
      { label: 'QR-Code (Girocode) zum Bezahlen anzeigen', text: 'Ist das Kästchen gesetzt, bietet der Zahlungsdialog Teilnehmenden zusätzlich einen Girocode zum Scannen mit der Banking-App an. Ohne Haken fehlt der Button.' },

      { label: 'Tab „Startseite“: Hinweisseite aktiviert', text: 'An: Besucher der Startseite und der Registrierungsseite sehen statt des Formulars einen Hinweis mit Logo, Nachricht und optional Countdown. Mitglieder können sich weiter über /login.html anmelden. Wirkt sofort.' },
      { label: 'Nachricht (HTML)', text: 'Frei gestaltbarer Text der Hinweisseite.' },
      { label: 'Countdown-Ziel', text: 'Optionaler Zeitpunkt (in Deiner Ortszeit), bis zu dem ein Countdown läuft. Leer = kein Countdown.' },
      { label: 'Vorschau öffnen', text: 'Öffnet die Hinweisseite in einem neuen Tab.' },

      { label: 'Tab „Branding“: App-Titel', text: 'Name der App, z. B. in Titel und Seitenleiste.' },
      { label: 'Event-Name', text: 'Bezeichnung des Events im Branding, z. B. „P17/2027“.' },
      { label: 'Logo-URL', text: 'Adresse eines Logos im Internet. Ein hochgeladenes Logo hat Vorrang vor dieser URL.' },
      { label: 'Speicher-Kontingent pro Charakter (MB)', text: 'Wie viel Dateispeicher (z. B. Bilder, Dokumente) ein einzelner Charakter belegen darf.' },
      { label: 'Theme-Modus', text: 'Hell oder Dunkel für die ganze Instanz.' },
      { label: 'Farbschema', text: 'Farbwelt der Oberfläche: Sahara, Ozean, Wald, Höhle, Horror/Gothic, jeweils auch „intensiv“, oder „Profi (eigene Farben)“.' },
      { label: 'Profi-Farbschema', text: 'Nur bei „Profi“: eigene Farbe für jede Rolle. Die Felder starten mit den Farben des zuletzt aktiven Schemas.' },
      { label: 'Hintergrund und Deckkraft', text: 'Wähle eine Grafik hinter allen Seiten und in der Seitenleiste. Die Vorlagen nehmen die Farbe des Farbschemas an. Die Deckkraft stellst Du von 0 bis 100 Prozent ein.' },
      { label: 'Speichern (Branding)', text: 'Übernimmt App-Titel, Event-Name, Logo-URL, Kontingent, Theme, Farbschema, Farben und Hintergrund. Die Bild-Uploads darunter wirken unabhängig davon.' },
      { label: 'Logo hochladen / Logo entfernen', text: 'Lade ein Logo (JPEG, PNG oder WebP) hoch. Es hat Vorrang vor der Logo-URL und erscheint auch im Anmelde-PDF.' },
      { label: 'Ticket-Hintergrund hochladen / entfernen', text: 'Bild, das blass als Wasserzeichen auf dem Event-Ticket im Konto-Dashboard erscheint.' },
      { label: 'Eigenes Hintergrundbild hochladen / entfernen', text: 'Wird instanzweit mit 20 Prozent Deckkraft hinter allen Seiten angezeigt und beim Hochladen automatisch als Hintergrund gewählt. Die vorgefertigten Hintergründe passen sich dagegen dem Farbschema an.' },

      { label: 'Tab „Speicher“: Backend', text: 'Wo hochgeladene Dateien liegen: Lokal (auf dem Server), FTP oder S3. Neue Dateien landen im gewählten Backend.' },
      { label: 'FTP-Felder', text: 'Host, Port, Benutzername, Passwort, Basis-Verzeichnis und „FTPS (verschlüsselt)“. Ein leeres Passwort behält das gespeicherte.' },
      { label: 'S3-Felder', text: 'Bucket, Region, Endpoint (nur für S3-kompatible Dienste), Access Key ID und Secret Access Key. Ein leerer Secret Key behält den gespeicherten.' },
      { label: 'Verbindung testen', text: 'Prüft die eingetragenen Zugangsdaten, ohne zu speichern.' },
      { label: 'Speichern (Speicher)', text: 'Speichert die Backend-Einstellungen. Bereits vorhandene Dateien bleiben zunächst am alten Ort.' },
      { label: 'Speicherverbrauch', text: 'Balkendiagramm, wie viel Speicher in Lokal, FTP und S3 belegt ist.' },
      { label: 'Migrieren', text: 'Verschiebt alle Dateien, die noch nicht auf dem aktiven Backend liegen, dorthin. Nach Rückfrage; fehlgeschlagene Dateien werden unten aufgelistet. Kann länger dauern.' },

      { label: 'Tab „Add-ons & Test“: Add-on Tavernenkonto', text: 'Guthabenkonten für die Taverne mit Getränkekarte, Aufladen und Abbuchen. Wenn aktiv, erscheint „Taverne“ in der Seitenleiste (für Admins und Rollen mit dem Menü „Taverne“), nach dem Neuladen der Seite.' },
      { label: 'Add-on Unterkünfte', text: 'Schlafplätze mit Bettenzahl, die Teilnehmer bei der Anmeldung buchen. Wenn aktiv, erscheint „Unterkünfte“ in der Administration (nach Neuladen).' },
      { label: 'Add-on PDF-Import', text: 'Liest ausgefüllte PDF-Anmeldeformulare ein. Wenn aktiv, erscheint „PDF-Import“ in der Seitenleiste.' },
      { label: 'Add-on PDF-Erzeugung', text: 'Erzeugt ein ausfüllbares Anmelde-PDF aus den Schema-Feldern. Wenn aktiv, erscheint „PDF-Erzeugung“ in der Seitenleiste.' },
      { label: 'Testdaten laden', text: 'Lädt einen fiktiven Datensatz: 75 Personen mit Charakteren, Anmeldungen in verschiedenen Status, ein Test-Event und eine Beispiel-Getränkekarte. Alles ist als Testdaten markiert, die Personen können sich nicht einloggen und bekommen keine E-Mails. Ist schon ein echtes Event aktiv, bleibt es aktiv; das Test-Event aktivierst Du unter Events. Die Seite lädt danach neu.' },
      { label: 'Testdaten entfernen', text: 'Nur sichtbar, wenn Testdaten geladen sind. Entfernt nach Rückfrage alle Testdaten vollständig; echte Daten bleiben erhalten.' },
    ],
  },

  '/admin/pdf-import.html': {
    title: 'PDF-Import',
    anchor: 'pdf-import',
    intro: 'Hier liest Du ausgefüllte PDF-Anmeldeformulare ein. Du ordnest die Felder der Vorlage einmal den App-Feldern zu, danach landen alle weiteren PDFs in der Datenbank.',
    items: [
      { label: 'Add-on nicht aktiviert', text: 'Ist der PDF-Import ausgeschaltet, siehst Du nur diesen Hinweis. Aktivieren kannst Du ihn unter Einstellungen im Tab „Add-ons & Test“.' },
      { label: '1. Vorlage & Feldzuordnung', text: 'Aufklappbarer Bereich. Er ist offen, solange noch keine Zuordnung gespeichert ist, danach eingeklappt.' },
      { label: 'Vorlagen-PDF', text: 'Lade ein leeres oder ausgefülltes Formular-PDF hoch. Die Formularfelder werden erkannt und Vorschläge anhand der Namen gemacht.' },
      { label: 'Felder automatisch erkennen', text: 'Füllt nur noch nicht zugeordnete Felder anhand ihrer Namen aus. Die Vorschläge sind markiert; prüfe sie und speichere danach.' },
      { label: 'Zuordnungstabelle', text: 'Pro PDF-Feld: Name, Typ (Text, Kontrollkästchen, Auswahl, Dropdown), die Zuordnung in der App (Einsender, Person OT, Anmeldung OT, Charakter IT) und bei Auswahlfeldern die Beschriftung der einzelnen Optionen. „– nicht übernehmen –“ ignoriert das Feld.' },
      { label: 'Eingangsbestätigung per E-Mail ermöglichen', text: 'Erlaubt, dem Einsender eine Bestätigung zu schicken. Funktioniert nur, wenn ein Feld „E-Mail des Einsenders“ zugeordnet ist.' },
      { label: 'Zuordnung speichern', text: 'Speichert die Zuordnung. Erst danach erscheint der Bereich „2. PDFs einlesen“.' },
      { label: 'Vorlage & Zuordnung zurücksetzen', text: 'Löscht Vorlage und Zuordnung nach Rückfrage. Bereits eingelesene PDFs bleiben erhalten.' },
      { label: '2. PDFs einlesen: Ausgefüllte Anmelde-PDFs', text: 'Wähle ein oder mehrere ausgefüllte PDFs aus.' },
      { label: 'Direktanmeldung für dieses Event', text: 'Standard ist „Nur speichern, keine Direktanmeldung anlegen“. Wählst Du ein Event, wird zusätzlich eine Direktanmeldung angelegt: eine Person ohne Login, die sich später unter Mitglieder in ein volles Konto umwandeln lässt. Klappt das nicht, steht der Grund hinter der Datei.' },
      { label: 'Eingangsbestätigung an die E-Mail-Adresse im PDF senden', text: 'Nur sichtbar, wenn Bestätigungen aktiviert und eine E-Mail-Zuordnung vorhanden ist. Schickt dem Einsender eine Mail.' },
      { label: 'Einlesen', text: 'Liest alle gewählten PDFs nacheinander ein. Pro Datei steht darunter Erfolg oder Fehler.' },
      { label: 'Tabelle der Importe', text: 'Eingegangen, Name, E-Mail, Datei, Direktanmeldung (Angelegt, Fehlgeschlagen oder –) und Bestätigung (Gesendet, Fehler oder –).' },
      { label: 'Anzeigen (Dialog)', text: 'Öffnet die eingelesenen Werte, gruppiert nach Einsender, Person, Anmeldung und Charakter, plus aufklappbar alle PDF-Rohwerte.' },
      { label: 'Als Direktanmeldung übernehmen', text: 'Im Dialog, solange noch keine Direktanmeldung existiert: Wähle ein Event und lege die Anmeldung nachträglich an.' },
      { label: 'Bestätigung senden', text: 'Im Dialog, nur wenn eine E-Mail-Adresse zugeordnet ist: Sendet die Eingangsbestätigung.' },
      { label: 'Löschen', text: 'Löscht den Import nach Rückfrage endgültig.' },
      { label: 'Schließen', text: 'Schließt den Dialog.' },
    ],
  },

  '/admin/pdf-export.html': {
    title: 'PDF-Erzeugung',
    anchor: 'pdf-export',
    intro: 'Hier lädst Du ein ausfüllbares Anmelde-PDF herunter, das aus Deinen Konto-, Anmelde-, OT- und IT-Feldern erzeugt wird.',
    items: [
      { label: 'Add-on nicht aktiviert', text: 'Ist die PDF-Erzeugung ausgeschaltet, siehst Du nur diesen Hinweis. Aktivieren kannst Du sie unter Einstellungen im Tab „Add-ons & Test“.' },
      { label: 'Vorlagen (Klassisch, Modern, Schlicht, Kompakt)', text: 'Jede Vorlage hat einen anderen Stil: Klassisch mit Serifenschrift, Modern zweispaltig mit Abschnittsbalken, Schlicht schwarz-weiß und druckfreundlich, Kompakt dreispaltig mit kleiner Schrift. Das Deckblatt zeigt das hochgeladene Logo und das Ticket-Motiv (PNG oder JPEG) aus den Einstellungen.' },
      { label: 'PDF herunterladen', text: 'Erzeugt das leere, ausfüllbare Formular der Vorlage und lädt es als PDF herunter. Änderungen am Schema wirken sich auf neu erzeugte PDFs aus.' },
    ],
  },

  '/admin/lodging.html': {
    title: 'Unterkünfte',
    anchor: 'unterkuenfte',
    intro: 'Hier legst Du die Schlafplätze eines Events an, die Teilnehmer bei der Anmeldung buchen, und siehst, wer wo schläft.',
    items: [
      { label: 'Add-on nicht aktiviert', text: 'Sind die Unterkünfte ausgeschaltet, siehst Du nur diesen Hinweis. Aktivieren kannst Du sie unter Einstellungen im Tab „Add-ons & Test“.' },
      { label: 'Event', text: 'Wähle das Event, dessen Unterkünfte Du bearbeitest. Vorausgewählt ist das aktive Event. Ohne Event musst Du zuerst eines anlegen.' },
      { label: '+ Unterkunft hinzufügen', text: 'Fügt eine neue Zeile hinzu (Standard: Betten, 2 Plätze). Gespeichert wird erst mit „Speichern“.' },
      { label: 'Bezeichnung', text: 'Name der Unterkunft, z. B. Hütte Eiche, Zimmer 12 oder Zeltwiese Nord (höchstens 100 Zeichen). Zeilen ohne Bezeichnung werden beim Speichern verworfen.' },
      { label: 'Art', text: '„Betten“ (Hütte, Zimmer, Zelt) mit fester Bettenzahl oder „Zeltplätze (eigenes Zelt)“ für Teilnehmer, die ein eigenes Zelt mitbringen.' },
      { label: 'Betten / Zeltplätze', text: 'Anzahl der Plätze (Betten 1 bis 500). Bei Zeltplätzen bedeutet 0 unbegrenzt viele Plätze.' },
      { label: 'Preis (€)', text: 'Preis pro Bett bzw. Zeltplatz. 0 = kostenlos.' },
      { label: 'Standard-Unterbringung', text: 'Pro Event nur eine möglich. Sie wird bei der Anmeldung immer angezeigt und vorausgewählt; die anderen Unterkünfte erst nach „Unterbringung mieten“.' },
      { label: 'Beschreibung', text: 'Optionaler Zusatztext, z. B. „mit Ofen, barrierefrei“.' },
      { label: '▲ / ▼', text: 'Ändert die Reihenfolge der Unterkünfte.' },
      { label: 'Entfernen', text: 'Entfernt die Zeile aus der Liste. Erst mit „Speichern“ wird sie wirklich gelöscht.' },
      { label: 'Speichern', text: 'Speichert alle Unterkünfte des Events. Bestehende Unterkünfte behalten ihre Kennung, weil Anmeldungen darauf verweisen.' },
      { label: 'Belegung', text: 'Pro Unterkunft: Markierung „Standard“, Anzahl belegter Plätze (bei Zeltplätzen mit 0 „unbegrenzt“) und die Namen der eingetragenen Personen. Bei Zelten stehen die angegebenen Maße dabei.' },
    ],
  },
};
