// Hilfetexte: Events, Check-In, Taverne (nur Daten).
export default {
  '/admin/events.html': {
    title: 'Events',
    anchor: 'events',
    intro: 'Hier legst du Events an, bearbeitest sie, aktivierst sie für die Anmeldung und beendest sie.',
    items: [
      { label: 'Neues Event', text: 'Öffnet das leere Event-Formular. Erst nach dem Speichern kannst du im Tab „Rundmail“ Mails senden.' },
      { label: 'Event-Liste: Name, Datum, Status', text: 'Zeigt alle Events mit Datum (bei mehrtägigen von – bis). „Aktiv – Anmeldung offen“ heißt: Teilnehmende melden sich für dieses Event an. „Beendet“ erscheint, wenn das Event beendet wurde.' },
      { label: 'Aktivieren', text: 'Macht dieses Event zum aktuellen Event, für das die Anmeldung läuft. Nur bei inaktiven Events sichtbar.' },
      { label: 'Event beenden', text: 'Markiert das Event als beendet. Erst danach ist im Check-In das Auschecken möglich. Außerdem startet ab jetzt die Frist für die Datenlöschung (Tab „Datenschutz“).' },
      { label: 'Wieder öffnen', text: 'Nimmt das Beenden zurück. Check-Out ist dann wieder gesperrt.' },
      { label: 'Bearbeiten', text: 'Öffnet das Event-Formular mit den gespeicherten Werten.' },
      { label: 'Löschen', text: 'Löscht das Event nach Rückfrage. Hat das Event noch Anmeldungen, öffnet sich stattdessen der Dialog „Event erzwungen löschen“.' },
      { label: 'Event erzwungen löschen (Dialog)', text: 'Löscht das Event samt allen Anmeldungen; alle Teilnehmer werden abgemeldet. Das kann nicht rückgängig gemacht werden.' },
      { label: 'Teilnehmer per E-Mail über die Absage informieren', text: 'Checkbox im Lösch-Dialog. Wenn gesetzt, bekommen alle Angemeldeten eine Absage-Mail.' },
      { label: 'Endgültig löschen / Abbrechen', text: '„Endgültig löschen“ führt das erzwungene Löschen aus, „Abbrechen“ schließt den Dialog ohne Änderung.' },
      { label: 'Tab Grunddaten', text: 'Name, Datum, Plätze, Zahlungsfreigabe und Sonderrollen des Events.' },
      { label: 'Name', text: 'Pflichtfeld. So heißt das Event überall in der App.' },
      { label: 'Startdatum', text: 'Pflichtfeld. Erster Tag des Events; auch Ziel des Countdowns im Widget.' },
      { label: 'Enddatum', text: 'Optional, für mehrtägige Events.' },
      { label: 'QR-Code-Kennung', text: 'Optional, z. B. P17/2027. Ist Teil der QR-Codes beim Check-In und wird für Link und Einbettungscode des Direktanmeldungs-Widgets gebraucht. Im internen Bereich identifiziert sie das Event, z. B. als Kürzel in der Mitgliederliste.' },
      { label: 'Plätze (geplant)', text: 'Optional. Leer bedeutet unbegrenzt. Das ist die Zahl der Plätze, mit der du planst.' },
      { label: 'Harte Obergrenze', text: 'Optional. Ab dieser Zahl gilt die Warteliste: weitere Anmeldungen kommen auf die Warteliste. Leer bedeutet, dass die geplanten Plätze die Grenze sind.' },
      { label: 'Hinweis „Nur noch wenige Plätze verfügbar“ anzeigen', text: 'Wenn gesetzt, sehen Teilnehmende einen Hinweis auf wenige freie Plätze.' },
      { label: 'ab … belegten Plätzen', text: 'Ab dieser Zahl belegter Plätze erscheint der Hinweis „Nur noch wenige Plätze“ (letzte Plätze). Leer bedeutet: ab der geplanten Platzzahl.' },
      { label: 'Farbe (neben der QR-Code-Kennung)', text: 'Farbe des Events. Sie markiert die Kennung in der Mitgliederliste mit einem farbigen Streifen, damit du Events auf einen Blick unterscheidest. „Keine Farbe“ entfernt sie wieder.' },
      { label: 'Zahlungen freigeben', text: 'Erst wenn das gesetzt ist, sehen Teilnehmende den Button „Jetzt bezahlen“. Vorher können sie sich anmelden, aber noch nicht zahlen.' },
      { label: 'Sonderrollen', text: 'Besondere Rollen des Events, z. B. GSC, VP oder Ersthelfer. Teilnehmende sehen sie bei der Anmeldung als Karten mit deiner Kurzbeschreibung und können mehrere wählen.' },
      { label: '+ Sonderrolle hinzufügen', text: 'Legt eine neue Zeile mit Bezeichnung und Beschreibung an. Zeilen ohne Bezeichnung werden nicht gespeichert.' },
      { label: 'Sonderrolle: Bezeichnung / Beschreibung', text: 'Bezeichnung (max. 60 Zeichen) und Kurzbeschreibung (max. 500 Zeichen) für die Teilnehmenden. Eine umbenannte Rolle behält ihre bisherigen Zuordnungen.' },
      { label: 'Sonderrolle: ▲ ▼ Entfernen', text: 'Pfeile ändern die Reihenfolge, „Entfernen“ löscht die Sonderrolle aus dem Event.' },
      { label: 'Tab Ort & Texte', text: 'Adresse, Karten-Links und Texte, die im Dashboard der Teilnehmenden erscheinen – jeweils nur, wenn ausgefüllt.' },
      { label: 'Adresse', text: 'Anschrift des Veranstaltungsorts. Daraus werden automatisch Google-Maps- und OpenStreetMap-Link erzeugt, solange du keine eigenen einträgst.' },
      { label: 'Google-Maps-Link / OpenStreetMap-Link', text: 'Optional. Überschreiben den automatisch erzeugten Link.' },
      { label: 'Anfahrtsbeschreibung', text: 'Optionaler Freitext zur Anreise.' },
      { label: 'Plot & Briefing', text: 'Optionaler Freitext mit Plot und Briefing für die Teilnehmenden.' },
      { label: 'Tab Preise & Extras', text: 'Teilnahmegruppen, Preisstufen und zubuchbare Extras.' },
      { label: 'Teilnahmegruppen', text: 'Gruppen mit unterschiedlichem Preis, z. B. Erwachsene und Kinder. Jede Gruppe wird ein Preisfeld in jeder Preisstufe.' },
      { label: '+ Teilnahmegruppe hinzufügen / Entfernen', text: 'Legt eine Gruppe an bzw. entfernt sie. Beim Umbenennen bleiben bereits eingegebene Preise erhalten.' },
      { label: 'Automatisch vorwählen, wenn', text: 'Bis zu drei Bedingungen pro Gruppe (alle müssen zutreffen). Auf Basis von Teilnahme-, Konto- oder Anmeldefeldern wird die Gruppe bei der Anmeldung automatisch vorgewählt, z. B. nach Alter. Mit „+ weitere Bedingung“ fügst du eine hinzu, mit „×“ entfernst du sie.' },
      { label: 'Preisstufen (nach Datum)', text: 'Zeitlich gestaffelte Preise, z. B. Frühbucher. Bei der Anmeldung gilt automatisch die erste noch gültige Stufe. Erst Teilnahmegruppen anlegen, dann Stufen.' },
      { label: 'Preisstufe / Gültig bis', text: 'Name der Stufe und letzter Tag, bis zu dem sie gilt. Leer bei „Gültig bis“ bedeutet: letzte Stufe ohne Ablauf.' },
      { label: 'Preisstufe: Betrag je Gruppe (€)', text: 'Pro Teilnahmegruppe der Preis in Euro in dieser Stufe.' },
      { label: 'Con-Zahler', text: 'Checkbox je Preisstufe. Wer in dieser Stufe bucht, zahlt erst vor Ort. Das Ticket wird trotzdem ausgestellt und die Person kann direkt eingecheckt werden.' },
      { label: '+ Preisstufe hinzufügen / Entfernen', text: 'Legt eine neue Stufe an bzw. entfernt sie. Stufen ohne Namen werden nicht gespeichert.' },
      { label: 'Zubuchbare Extras', text: 'Zusatzangebote gegen Aufpreis, z. B. Hüttenplatz oder Stellplatz. Teilnehmende buchen sie mit Menge bei der Anmeldung; der Preis wird zum Anmeldebetrag addiert.' },
      { label: 'Extra: Bezeichnung / Preis (€) pro Stück / Kontingent / Beschreibung', text: 'Name, Stückpreis, optionales Kontingent (begrenzt die Gesamtmenge über alle Anmeldungen, leer = unbegrenzt) und optionale Beschreibung.' },
      { label: '+ Extra hinzufügen / Entfernen', text: 'Legt ein Extra an bzw. entfernt es. Extras ohne Bezeichnung werden nicht gespeichert.' },
      { label: 'Tab Direktanmeldungs-Widget', text: 'Link und Einbettungscodes, mit denen sich Personen ohne Konto ein Ticket sichern können, z. B. auf eurer Website. Braucht eine QR-Code-Kennung im Tab Grunddaten, sonst steht hier nur ein Hinweis.' },
      { label: 'Direkter Link', text: 'Adresse der eigenständigen Ticket-Seite für dieses Event.' },
      { label: 'Ticket-Formular einbetten (Script)', text: 'Code für das Ticket-Formular auf deiner Website. Das Formular übernimmt Schrift und Textfarbe der Seite; die Buttonfarbe lässt sich über die CSS-Variable --pk-accent ändern.' },
      { label: 'Countdown mit Button einbetten (Script)', text: 'Code für einen Countdown mit Button. Er zählt bis zum Eventdatum, mit data-until bis zu einem eigenen Zeitpunkt (z. B. Vorverkaufsstart).' },
      { label: 'Für React, Next.js, Vue & Co. (Platzhalter)', text: 'Frameworks führen Script-Tags aus Templates nicht aus. Lade dort widget.js einmal im Layout und setze die Platzhalter an die gewünschte Stelle.' },
      { label: 'Kopieren', text: 'Kopiert das jeweilige Feld in die Zwischenablage. Klappt das nicht, ist der Text markiert und du kopierst ihn mit Strg/Cmd+C.' },
      { label: 'Tab Datenschutz', text: 'Legt fest, wann welche Daten nach dem Event gelöscht werden. Anmeldungsfelder werden immer gelöscht; Konto- und Charakterfelder nur bei Teilnehmenden, die der Speicherung für weitere Events nicht zugestimmt haben.' },
      { label: 'Löschen nach (Tagen)', text: 'Je Datenart: Anzahl Tage nach „Event beenden“, nach denen gelöscht wird.' },
      { label: 'Art der Löschung', text: '„Automatisch“ löscht von selbst. „Nach Benachrichtigung“ meldet die Fälligkeit und löscht erst, wenn du bestätigst.' },
      { label: 'Feldzuordnung', text: 'Ordnet jedes Feld aus den Feldschemas einer Datenart zu. Nicht zugeordnete Felder werden von dieser Regel nicht erfasst.' },
      { label: 'Automatisch erkennen', text: 'Ordnet noch nicht zugeordnete Felder anhand von Bezeichnung und Schlüssel zu. Bitte danach prüfen.' },
      { label: 'Stand der Löschung / Jetzt löschen', text: 'Nur bei gespeicherten Events: zeigt je Datenart, ob schon gelöscht wurde oder wann es fällig ist. „Jetzt löschen“ erscheint bei fälligen Daten und löscht sie nach Rückfrage endgültig.' },
      { label: 'Tab Rundmail', text: 'Eine E-Mail an Angemeldete oder frei eingegebene Adressen senden. Verfügbar erst, wenn das Event gespeichert ist.' },
      { label: 'Betreff und Nachricht', text: 'Betreff (max. 200 Zeichen) und Text. Die Symbolleiste bietet Fett, Kursiv, Unterstrichen, Überschrift, Listen, Link, Bild per Adresse und „Formatierung entfernen“.' },
      { label: '</> HTML', text: 'Wechselt zwischen Texteditor und HTML-Quelltext. Skripte und Formulare werden beim Senden entfernt.' },
      { label: 'Alle Angemeldeten dieses Events anschreiben', text: 'Schaltet die Empfänger aus den Anmeldungen ein.' },
      { label: 'Nach Kriterien filtern', text: 'Schränkt die Empfänger ein: Status (alle außer Abgesagt vorgewählt), Rolle (keine Auswahl = alle Rollen), Zahlung (egal / nur Bezahlte / nur Unbezahlte) und „Nur Gast-Anmeldungen (ohne Konto)“.' },
      { label: 'Weitere E-Mail-Adressen', text: 'Zusätzliche Empfänger, kommagetrennt. Unter dem Feld siehst du die Empfängerzahl; ungültige Adressen, Anmeldungen ohne E-Mail und die Obergrenze pro Rundmail werden dort gemeldet.' },
      { label: 'Testmail an mich', text: 'Schickt die Mail nur an dich, zur Kontrolle. Sie erscheint im Verlauf mit dem Vermerk „Test“.' },
      { label: 'Rundmail senden', text: 'Sendet die Mail nach Rückfrage an alle Empfänger. Das lässt sich nicht zurückholen. Ein Fortschritt wird angezeigt.' },
      { label: 'Bisher gesendet', text: 'Verlauf aller Rundmails mit Zeitpunkt, Absender, Anzahl gesendet und fehlgeschlagener Adressen.' },
      { label: 'Abbrechen / Speichern', text: '„Speichern“ (bei bestehenden Events „Änderungen speichern“) legt das Event an bzw. übernimmt die Änderungen aus allen Tabs. „Abbrechen“ verwirft das Formular.' }
    ]
  },

  '/admin/checkin.html': {
    title: 'Check-In',
    anchor: 'checkin',
    intro: 'Hier checkst du Teilnehmende am Eingang ein, pflegst Zahlungen und Rollen und gibst nach dem Event das Auschecken frei.',
    items: [
      { label: 'Als eigene Vollbild-Seite öffnen (/checkin)', text: 'Öffnet den Check-In ohne Menü als eigene Seite, praktisch für Tablet oder Handy am Eingang.' },
      { label: 'Event-Auswahl', text: 'Wählt das Event, dessen Teilnehmerliste angezeigt wird. Es stehen nur aktive Events zur Auswahl.' },
      { label: 'Event beenden (Check-Out freigeben) / Event wieder öffnen', text: 'Nur mit dem Menü „Events“ sichtbar. Beenden gibt das Auschecken frei, Wieder öffnen nimmt das zurück.' },
      { label: 'Gesamt / Eingecheckt', text: 'Zähler: Anzahl aller Personen in der Liste und Anzahl der aktuell eingecheckten Personen.' },
      { label: 'QR-Scan: Aus / Push / An', text: 'Aus: Kamera bleibt aus. Push: die Kamera startet nur per Button „Scan starten (20s)“ und stoppt nach 20 Sekunden. An: die Kamera läuft dauerhaft. Die Wahl wird im Browser gespeichert. Die Kamera braucht eine gesicherte Verbindung (https) und deine Freigabe.' },
      { label: 'Scan starten (20s)', text: 'Nur im Modus Push sichtbar. Startet die Kamera für 20 Sekunden.' },
      { label: 'Licht / Scan beenden', text: 'Im Kamerabild: „Licht“ schaltet die Taschenlampe ein, wenn das Gerät sie unterstützt. „Scan beenden“ stoppt die Kamera. Wechselt die Seite in den Hintergrund, pausiert der Scan automatisch.' },
      { label: 'Gescannter Teilnehmer (Dialog)', text: 'Erscheint nach einem erkannten QR-Code und zeigt Name, Kategorie (mit Sonderrollen), Status und Charaktere. „Einchecken“ ist nur möglich bei Status Bestätigt oder bei Con-Zahlern mit Status Angemeldet. Sonst steht eine Warnung wie „Noch nicht freigegeben“ oder „Bereits eingecheckt“. Der Dialog schließt nach 30 Sekunden von selbst.' },
      { label: 'Einchecken / Abbrechen (Scan-Dialog)', text: '„Einchecken“ startet den Check-In. Ist noch keine Zahlung gebucht, fragt die App vorher, ob die Person wirklich gezahlt hat. „Abbrechen“ schließt den Dialog; derselbe Code wird 5 Sekunden lang nicht erneut erkannt.' },
      { label: 'Angaben prüfen (Dialog)', text: 'Erscheint vor dem Check-In, wenn für das Event Felder mit „Beim Check-in erneut abfragen“ markiert sind. Gruppiert nach Konto, Anmeldung und Charakter; du kannst die Angaben mit der Person durchgehen und korrigieren.' },
      { label: 'Bestätigen & einchecken / Abbrechen (Angaben prüfen)', text: 'Speichert die Angaben und checkt dann ein. „Abbrechen“ schließt ohne Check-In.' },
      { label: 'Zahlungserinnerungen senden', text: 'Schickt nach Rückfrage eine Erinnerungs-Mail an alle Teilnehmenden dieses Events mit offener Zahlung. Danach siehst du, wie viele von wie vielen verschickt wurden.' },
      { label: 'Spalten ein- und ausblenden', text: 'Klappbarer Bereich zur Auswahl der Tabellenspalten. Die Einstellung wird in diesem Browser gespeichert; Name und Aktionen sind immer sichtbar.' },
      { label: 'Spalten: Tabelle', text: 'Schaltet die Standardspalten Charaktere, Rolle, Unterkunft (nur bei aktivierter Unterkunftsverwaltung), Extras, Betrag, Zahlung, Status und Override ein oder aus.' },
      { label: 'Spalten: Charakter-Felder (IT)', text: 'Zusätzliche Spalten mit Feldern der Charaktere.' },
      { label: 'Spalten: Mitglieder-Felder (OT)', text: 'Zusätzliche Spalten mit Konto- und Anmeldefeldern. Es werden nur die Felder angeboten, die du sehen darfst.' },
      { label: 'Reihenfolge zurücksetzen', text: 'Stellt die Standardreihenfolge der Spalten wieder her. Umsortieren geht per Drag & Drop an der Spaltenüberschrift.' },
      { label: 'Suche', text: 'Filtert die Liste nach Name oder Charakter.' },
      { label: 'CSV exportieren', text: 'Nur mit dem Recht zum Mitglieder-Export sichtbar. Lädt die gerade angezeigte Liste (mit Suchfilter) als CSV herunter.' },
      { label: 'Spalte Name', text: 'Name der Person.' },
      { label: 'Spalte Charaktere', text: 'Namen der Charaktere der Person.' },
      { label: 'Spalte Rolle', text: 'Rolle auf dem Event (Teilnehmer/SC, NSC, Helfer, Orga, Hilfs-Orga, Direktanmeldung), dazu Sonderrollen als Marken und „auch NSC-bereit“. Bei NSC steht der feste NSC oder „Springer“.' },
      { label: 'Rolle ändern', text: 'Nur mit dem Recht zum Status-Override. Öffnet den Dialog „Rolle ändern“.' },
      { label: 'Rolle ändern (Dialog)', text: 'Rolle wählen. Für SC ist ein Charakter nötig, bei NSC optional (ohne Charakter = Springer), alle anderen Rollen haben keinen Charakter. Bei NSC erscheinen zusätzlich die NSC-Felder. Hat das Event Sonderrollen, kannst du sie hier ankreuzen. „Speichern“ übernimmt, „Abbrechen“ schließt.' },
      { label: 'Spalte Unterkunft', text: 'Gebuchte Unterkunft. Nur sichtbar, wenn die Unterkunftsverwaltung aktiv ist.' },
      { label: 'Spalte Extras', text: 'Zugebuchte Extras der Anmeldung.' },
      { label: 'Spalte Betrag', text: 'Oben der Betrag in Euro, den die Person zahlen soll (leer = kein Betrag), darunter ein Feld für einen Rabatt in Euro. Darüber steht Teilnahmegruppe und Preisstufe. Änderungen werden beim Verlassen des Feldes gespeichert.' },
      { label: 'Spalte Zahlung', text: 'Zeigt „Offen“ bzw. bei Con-Zahlern „Zahlt vor Ort“, oder „Bezahlt“ mit Zahlungsart (Karte, PayPal, Überweisung). Ohne Betrag steht dort ein Strich.' },
      { label: 'Als bezahlt markieren', text: 'Bucht die Zahlung manuell als erhalten, z. B. bei Barzahlung oder Überweisung.' },
      { label: 'Zurücksetzen (Zahlung)', text: 'Setzt eine bezahlte Anmeldung wieder auf unbezahlt.' },
      { label: 'Erstatten', text: 'Fragt nach dem Betrag (vorbelegt mit dem vollen Betrag) und bucht nach Bestätigung eine Erstattung. Danach steht „Vollständig erstattet“ oder „Teilerstattet“ mit Betrag.' },
      { label: 'Spalte Status', text: 'Aktueller Status der Anmeldung, siehe unten. Bei Con-Zahlern steht „, Con-Zahler“ dahinter.' },
      { label: 'Status Warteliste', text: 'Die Person steht auf der Warteliste, weil die harte Obergrenze erreicht ist. Kein Platz, kein Check-In.' },
      { label: 'Status Angemeldet', text: 'Die Person ist angemeldet, aber noch nicht bezahlt. Einchecken geht nur bei Con-Zahlern, die vor Ort zahlen.' },
      { label: 'Status Bestätigt', text: 'Bezahlt bzw. freigegeben. Die Person ist bereit zum Einchecken.' },
      { label: 'Status Eingecheckt', text: 'Die Person ist angekommen. Eingecheckte wandern in der Liste nach unten.' },
      { label: 'Status Ausgecheckt', text: 'Die Person hat das Event verlassen. Geht erst, nachdem das Event beendet wurde.' },
      { label: 'Status Abgesagt', text: 'Die Anmeldung wurde storniert.' },
      { label: 'Status Benachrichtigt', text: 'Es gibt eine offene Einladung, aber noch keine Anmeldung. Hier gibt es nur „Einladung zurückziehen“.' },
      { label: 'Überweisung gemeldet (Zähler und Markierung)', text: 'Mit „Zurücksetzen“ neben der Markierung nimmst du die Meldung zurück, wenn kein Geld eingegangen ist (mit Rückfrage). Der Zähler oben zeigt, wie viele Teilnehmende „Ich habe überwiesen“ geklickt haben und noch nicht als bezahlt markiert sind. In der Zeile steht dann die Markierung „Überweisung gemeldet“ (mit Datum im Tooltip). Schau im Bankkonto nach und markiere die Zahlung als bezahlt.' },
      { label: 'Check-In', text: 'Checkt die Person ein. Aktiv bei Status Bestätigt (und bei Con-Zahlern mit Status Angemeldet). Fehlt die Zahlung, fragt die App vorher nach; eventuell folgt der Dialog „Angaben prüfen“.' },
      { label: 'Check-Out', text: 'Erst sichtbar, wenn das Event beendet wurde, und nur bei eingecheckten Personen aktiv.' },
      { label: 'Einladung zurückziehen', text: 'Nur mit dem Recht zum Status-Override und nur bei Status Benachrichtigt. Nimmt die Einladung zurück, die Person verschwindet nach Rückfrage aus der Liste. So werden z. B. gelöschte Konten los.' },
      { label: 'Spalte Override (Status-Dropdown)', text: 'Nur mit dem Recht zum Status-Override. Setzt den Status direkt auf einen beliebigen Wert. Vor- und Rückwärtssprünge, die Schritte überspringen, musst du bestätigen.' },
      { label: 'Spaltenüberschriften ziehen', text: 'Per Drag & Drop auf eine andere Überschrift ändert sich die Reihenfolge der Spalten. Sie wird in diesem Browser gespeichert.' },
      { label: 'Hotkeys', text: 'Im Scan-Dialog bestätigt Enter das Einchecken und Escape bricht ab. Im Modus Push startet die Leertaste den Scan. Die Tasten sind in deinem Profil änderbar. In Eingabefeldern sind Hotkeys aus.' }
    ]
  },

  '/admin/tavern.html': {
    title: 'Taverne',
    anchor: 'taverne',
    intro: 'Die Taverne verwaltet Guthabenkonten für die Getränke- und Speisekasse eines Events. Ist das Modul nicht aktiviert, meldet die Seite, dass das Tavernenkonto nicht aktiviert ist.',
    items: [
      { label: 'Als eigene Vollbild-Seite öffnen (/taverne)', text: 'Öffnet die Taverne ohne Menü als eigene Seite, praktisch für ein Kassen-Tablet.' },
      { label: 'Event', text: 'Wählt das Event, dessen Konten und Buchungen du siehst. Vorausgewählt ist das aktive Event.' },
      { label: 'Tab Kasse', text: 'Konto suchen, Getränke abbuchen und Guthaben aufladen.' },
      { label: 'Kasse: Suche', text: 'Suche nach Nummer, Name oder Charakter. Die Trefferliste zeigt Nummer, Name, Guthaben und ggf. „Gesperrt“. Ein Klick öffnet das Konto.' },
      { label: 'Kontoansicht: Guthaben, Gesperrt', text: 'Zeigt Tavernen-Nummer, Name, Charaktere und das aktuelle Guthaben. „Gesperrt“ erscheint, wenn das Konto gesperrt ist.' },
      { label: 'Abbuchen: Getränkekarte-Kacheln', text: 'Jede aktive Karte hat eine Kachel, nach Kategorie sortiert. Klick auf die Kachel oder + erhöht die Menge, − verringert sie (max. 99). Ist die Karte leer, steht ein Hinweis, Artikel unter „Getränkekarte“ anzulegen.' },
      { label: 'Sonstiger Betrag (€)', text: 'Zusätzlicher freier Betrag, der zur Summe addiert wird.' },
      { label: 'Summe', text: 'Gesamtbetrag des Warenkorbs. Eine Warnung erscheint, wenn das Konto gesperrt ist oder das Guthaben nicht reicht; dann ist Abbuchen gesperrt.' },
      { label: 'Leeren', text: 'Setzt den Warenkorb und den sonstigen Betrag zurück.' },
      { label: 'Abbuchen', text: 'Bucht die Summe vom Guthaben ab. Ein erneuter Klick nach einem Verbindungsfehler bucht nicht doppelt.' },
      { label: 'Aufladen: 5 € / 10 € / 20 € / 50 €', text: 'Schnellwahl, die den Betrag im Feld einträgt.' },
      { label: 'Betrag (€) und Zahlungsart', text: 'Betrag und Art der Einzahlung: Bar, Karte, PayPal oder Überweisung. Die Zahlungsart dient nur der Abrechnung.' },
      { label: 'Aufladen (Button)', text: 'Bucht den Betrag als Guthaben auf das Konto.' },
      { label: 'Verlauf', text: 'Alle Buchungen des Kontos (Abbuchung, Aufladung, Auszahlung, Storno) mit Zeitpunkt und Betrag.' },
      { label: 'Storno', text: 'Stellt eine Buchung nach Rückfrage rückgängig. Die Buchung bleibt als „storniert“ im Verlauf und zählt in der Abrechnung nicht mit.' },
      { label: 'Restguthaben auszahlen', text: 'Nur sichtbar, wenn Guthaben vorhanden ist. Bucht nach Rückfrage das gesamte Restguthaben als Auszahlung aus. Ist das Event vorbei, wird zusätzlich darauf hingewiesen.' },
      { label: 'Konto sperren / Konto entsperren', text: 'Ein gesperrtes Konto kann nichts abbuchen. Mit dem Button hebst du die Sperre wieder auf.' },
      { label: 'Tab Konten', text: 'Konten anlegen und Übersicht aller Konten des Events.' },
      { label: 'Angemeldete Person suchen', text: 'Sucht angemeldete Personen ohne Konto nach Name oder Charakter. Ein Klick auf ein Ergebnis legt ein verknüpftes Konto an; so findet man es auch über OT- und IT-Namen.' },
      { label: 'Bezeichnung (ohne Person) / Konto anlegen', text: 'Legt ein Konto ohne Anmeldung an, z. B. für Laufkundschaft wie „Händler am Tor“. Die Bezeichnung ist Pflicht.' },
      { label: 'Kontotabelle: Nr., Name, Charaktere, Guthaben, Status', text: 'Alle Konten des Events. Status zeigt „Gesperrt“, falls das Konto gesperrt ist.' },
      { label: 'Tab Getränkekarte', text: 'Artikel der Kasse pflegen.' },
      { label: 'Artikel hinzufügen: Name, Kategorie, Preis (€)', text: 'Neuer Artikel für die Kasse. Name und Preis sind Pflicht. Die Kategorie gruppiert die Kacheln, z. B. Bier, Met, Speisen.' },
      { label: 'Artikeltabelle: Name, Kategorie, Preis (€), Aktiv', text: 'Alle Artikel direkt bearbeitbar. Nur aktive Artikel erscheinen an der Kasse.' },
      { label: 'Speichern (Artikel)', text: 'Übernimmt die Änderungen der Zeile.' },
      { label: 'Löschen (Artikel)', text: 'Löscht den Artikel nach Rückfrage. Bereits gebuchte Abbuchungen bleiben unverändert.' },
      { label: 'Tab Abrechnung', text: 'Auswertung für einen Zeitraum. Stornierte Buchungen zählen nicht mit.' },
      { label: 'Von / Bis', text: 'Zeitraum der Auswertung. Standard ist heute; ist „Bis“ leer, gilt nur der Tag von „Von“.' },
      { label: 'Anzeigen', text: 'Lädt die Auswertung: Umsatz (Abbuchungen), Aufladungen, Auszahlungen, Stornos, offenes Guthaben auf allen Konten, Aufladungen nach Zahlungsart und Umsatz je Artikel.' },
      { label: 'Buchungen als CSV', text: 'Lädt die einzelnen Buchungen des gewählten Zeitraums als CSV herunter.' }
    ]
  }
};
