export default {
  '/admin/members.html': {
    title: 'Mitglieder',
    anchor: 'mitglieder',
    intro: 'Hier verwaltest du alle Konten: suchen, filtern, bearbeiten, einladen, Anmeldungen ändern und Listen exportieren.',
    items: [
      { label: 'Neues Mitglied anlegen', text: 'Öffnet den Einladungs-Dialog. Die Person bekommt einen Link, über den sie ihr Passwort setzt und das Konto aktiviert.' },
      { label: 'Aktive Mitglieder', text: 'Zeigt alle Personen mit einem Konto, das sich einloggen kann. Das ist die Standardansicht.' },
      { label: 'Eingeladene Mitglieder', text: 'Zeigt Einladungen, die noch nicht eingelöst wurden, also noch ohne Konto. Du kannst sie erneut senden oder zurückziehen.' },
      { label: 'Deaktivierte Mitglieder', text: 'Zeigt nur gesperrte Konten. Dort kannst du sie reaktivieren oder endgültig löschen.' },
      { label: 'Suche', text: 'Sucht live nach Name, Rufname, E-Mail, Rolle, Spielgruppe und dem Namen der verwaltenden Person.' },
      { label: 'Rolle (Filter)', text: 'Zeigt nur Mitglieder mit der gewählten Rolle. Es werden nur Rollen angeboten, die in der aktuellen Liste vorkommen.' },
      { label: 'Kontoart', text: 'Filtert nach Art des Kontos: Vollkonten, Verwaltete Personen (von jemand anderem betreut), Direktanmeldungen (Gäste ohne eigenes Konto), Eingeladen, Mit Discord oder Ohne Discord.' },
      { label: 'Kinder (Add-on)', text: 'Nur mit aktivem Add-on „Kinder“. Kinder tragen das Badge „Kind“ beim Namen. Die Kontoart bietet zusätzlich „Kinder“ und „Ohne Kinder“, „Sortieren nach“ zusätzlich „Kinder zuerst“ und „Kinder zuletzt“, „Gruppieren nach“ zusätzlich „Kinder / Erwachsene“. Der Zähler zeigt, wie viele Kinder in der Liste sind und wie viele davon gerade eingecheckt (anwesend) sind, mit gewähltem Event nur für dieses Event. Im Bearbeiten-Dialog einer verwalteten Person lässt sich die Markierung „Kind“ setzen oder entfernen.' },
      { label: 'Event', text: 'Wählt ein Event. Dann zeigt die Liste nur noch die Anmeldungen und Rollen für dieses Event, und der Filter „Anmeldung zum Event“ wird frei.' },
      { label: 'Anmeldung zum Event', text: 'Nur mit gewähltem Event aktiv. Filtert nach Anmeldestatus: Angemeldet oder bestätigt (ohne abgesagt), Nicht angemeldet, Angemeldet (noch nicht bezahlt), Bestätigt (bezahlt), Eingecheckt, Warteliste oder Abgesagt.' },
      { label: 'Sortieren nach', text: 'Sortiert nach Name, E-Mail, Rolle oder Status, aufsteigend oder absteigend. Ein Klick auf eine Spaltenüberschrift wirkt genauso. Einträge ohne Wert stehen immer unten.' },
      { label: 'Gruppieren nach', text: 'Teilt die Liste in Abschnitte nach Rolle, SC / NSC / Sonderrollen, Event, Anmeldestatus oder Spielgruppe (die Gruppe aus der Gruppenstruktur; verwaltete Personen zählen zur Gruppe ihres Verwalters). Filter, Suche und das gewählte Event gelten weiter, innerhalb jedes Abschnitts gilt die Sortierung. Wer mehrere Werte hat (z. B. zwei Events), steht in jedem passenden Abschnitt; wer keinen hat, steht im letzten Abschnitt („Ohne …“). Ein Klick auf eine Abschnitts-Überschrift klappt ihn ein oder aus. Der Zähler oben zählt jede Person nur einmal.' },
      { label: 'Zähler', text: 'Zeigt, wie viele Mitglieder angezeigt werden (bei aktiven Filtern „x von y“). Deine Filter und Sortierung merkt sich der Browser.' },
      { label: 'Zurücksetzen', text: 'Setzt Suche, Filter und Sortierung auf den Anfang zurück. Der Button erscheint nur, wenn etwas verstellt ist.' },
      { label: 'CSV exportieren', text: 'Lädt die angezeigte Liste (mit Filtern und Sortierung) als CSV herunter. Nur sichtbar mit dem Recht „CSV-Export“. Welche Felder drin sind, hängt von deiner Rolle ab. Der Vorgang wird im Protokoll festgehalten.' },
      { label: 'Auswahl exportieren', text: 'So heißt der Export-Button, sobald du Zeilen angehakt hast. Dann werden nur die ausgewählten Mitglieder exportiert.' },
      { label: 'CSV importieren', text: 'Nur für Admins. Du wählst eine CSV-Datei und siehst zuerst eine Vorschau mit Neu, Aktualisieren und Fehlern. Importiert wird erst nach einem Klick auf „Importieren“.' },
      { label: 'NSC-Übersicht', text: 'Öffnet eine Tabelle aller NSC-Anmeldungen der aktuellen Liste (ohne abgesagte) mit ihren NSC-Angaben. „Drucken“ druckt nur die Tabelle. Ohne NSC in der Liste kommt nur ein Hinweis.' },
      { label: 'Bulk-Leiste', text: 'Erscheint, sobald du Zeilen angehakt hast, und zeigt die Anzahl der Ausgewählten. Die Aktionen gelten für alle ausgewählten Mitglieder auf einmal; Fehlschläge werden danach einzeln aufgelistet.' },
      { label: 'Rolle ändern …', text: 'Bulk-Aktion: gibt allen Ausgewählten die gewählte Rolle. Nur sichtbar, wenn du Rollen ändern darfst.' },
      { label: 'Deaktivieren', text: 'Bulk-Aktion in der Ansicht „Aktive“: sperrt die Ausgewählten, meldet sie sofort ab und storniert ihre offenen Anmeldungen für kommende Events.' },
      { label: 'Reaktivieren', text: 'Bulk-Aktion in der Ansicht „Deaktivierte“: schaltet die Ausgewählten wieder frei.' },
      { label: 'Anmeldestatus …', text: 'Bulk-Aktion für ein gewähltes Event: „Bestätigen“ (Zahlung eingegangen) oder „Absagen“ (inklusive Nachrücken von der Warteliste). Nur sichtbar mit dem Recht, Status frei zu setzen. Es ändern sich nur Anmeldungen, bei denen der Wechsel erlaubt ist.' },
      { label: 'Auswahl aufheben', text: 'Entfernt alle Haken. Die Auswahl gilt nur für sichtbare Zeilen: Wenn du Filter oder Suche änderst, fallen ausgeblendete Zeilen raus.' },
      { label: 'Alle auswählen (Kästchen in der Kopfzeile)', text: 'Wählt alle angezeigten Mitglieder aus. Eingeladene und dein eigenes Konto lassen sich nicht auswählen.' },
      { label: 'Grüner Punkt vor dem Namen', text: 'Die Person hat bezahlt (für das gewählte Event, sonst für irgendeine ihrer Anmeldungen). Abgesagte Anmeldungen zählen nicht.' },
      { label: 'Spalte Name', text: 'Zeigt „Vorname Nachname / Rufname“. Ein Discord-Symbol zeigt, dass ein Discord-Konto verknüpft ist.' },
      { label: 'Spalte E-Mail', text: 'Die E-Mail-Adresse des Kontos. Bei verwalteten Personen oder Direktanmeldungen kann sie leer sein.' },
      { label: 'Spalte Rolle', text: 'Die Rolle des Mitglieds im Tool. Sie bestimmt, welche Menüs und Felder die Person sieht.' },
      { label: 'Spalte SC / NSC / Sonderrollen', text: 'Zeigt die Con-Rolle aus den nicht abgesagten Anmeldungen (SC, NSC, Helfer, Hilfs-Orga, Orga, Direktanmeldung) und dazu die Sonderrollen. Mit gewähltem Event nur für dieses Event.' },
      { label: 'Spalte Event', text: 'Die QR-Code-Kennung des Events (sonst der Name), zu dem die Person angemeldet ist, eine Zeile pro Anmeldung, in der Farbe des Events. Kennung und Farbe legst du in den Event-Einstellungen fest. Mit einem Event im Filter siehst du nur dieses.' },
      { label: 'Spalte Status', text: 'Zeigt pro Anmeldung (in derselben Zeile wie das Event) den Anmeldestatus als Dropdown. Wer das Recht zum Status-Ändern nicht hat, sieht nur den Text. Das Badge „Verwaltet von …“ oder „Direktanmeldung“ steht beim Namen. Bei Eingeladenen erscheint „Einladung abgelaufen“, wenn der Link nicht mehr gilt. Ob ein Konto aktiv, eingeladen oder deaktiviert ist, siehst du an den drei Tabs oben.' },
      { label: 'Überweisung gemeldet (Markierung und Pfeil)', text: 'Neben dem Status steht die Markierung, wenn jemand „Ich habe überwiesen“ geklickt hat und noch keine Zahlung gebucht ist: Du kannst einen Bankeingang erwarten. Der Tooltip zeigt, wann die Meldung kam. Kommt kein Geld, setzt der Pfeil-Button die Meldung zurück (mit Rückfrage), danach kann die Person erneut melden. Nach drei Tagen ohne Buchung erinnert dich das Dashboard.' },
      { label: 'Anmelden (Button in der Liste)', text: 'Steht in der Status-Spalte bei Personen ohne Anmeldung (nur für Admins und Moderatoren). Öffnet den Detail-Dialog direkt im Tab „Anmeldungen“, mit dem Event aus dem Filter vorausgewählt. Dort legst du Rolle, Charakter und Angaben fest und meldest die Person an.' },
      { label: 'Spalten ein- und ausblenden', text: 'Aufklappbarer Bereich über der Tabelle. Mit den Kästchen schaltest du Name, E-Mail, Rolle, SC/NSC/Sonderrollen, Event und Status an oder aus. Die Auswahl gilt nur für dich und wird in diesem Browser gespeichert; ein anderes Konto im selben Browser hat seine eigene.' },
      { label: 'Anmeldestatus-Dropdown', text: 'Pro Anmeldung ein Dropdown in der Status-Spalte, nur mit dem Recht, Status frei zu setzen. Stufen: Warteliste, Angemeldet (noch nicht bezahlt), Bestätigt (bezahlt/freigegeben), Eingecheckt, Ausgecheckt, Abgesagt. Beim Zurücksetzen, Überspringen oder Absagen fragt das Tool nach.' },
      { label: 'Bearbeiten (Stift)', text: 'Öffnet den Detail-Dialog des Mitglieds mit den Tabs Konto, Charaktere und Anmeldungen.' },
      { label: 'Deaktivieren (Person mit Strich)', text: 'Sperrt den Login, beendet alle laufenden Sitzungen sofort und storniert offene Anmeldungen (ausstehend, bestätigt, Warteliste) für kommende Events, damit die Person keinen Platz mehr belegt. Eingecheckte Anmeldungen und vergangene Events bleiben unverändert. Dein eigenes Konto hat den Button nicht. Rückgängig über „Reaktivieren“, die stornierten Anmeldungen kommen dabei aber nicht zurück.' },
      { label: 'Konvertierungslink (Pfeile)', text: 'Nur bei Direktanmeldungen mit E-Mail. Erzeugt einen Link, mit dem die Person ihre Direktanmeldung in ein volles Konto umwandeln kann. Er wird unter der Tabelle angezeigt und kann kopiert werden.' },
      { label: 'Zugriffslink (Schlüssel)', text: 'Nur bei aktiven Vollkonten. Erzeugt nach Rückfrage einen Link, mit dem sich die Person ohne Passwort anmelden kann. Weitergeben nur an die richtige Person.' },
      { label: 'Reaktivieren (Zeile)', text: 'Bei deaktivierten Mitgliedern: schaltet das Konto wieder frei.' },
      { label: 'Löschen', text: 'Bei deaktivierten Mitgliedern: löscht das Konto nach Rückfrage endgültig. Das lässt sich nicht rückgängig machen.' },
      { label: 'Erneut senden', text: 'Bei Eingeladenen: schickt die Einladung noch einmal und zeigt den Link unten an.' },
      { label: 'Aktivieren', text: 'Nur für Admins, bei Eingeladenen: legt das Konto sofort als aktives Mitglied an, ohne dass die Person den Einladungslink einlöst – z. B. wenn die Mail nie ankam. Das Konto hat noch kein Passwort; danach wird der Zugriffslink angezeigt, den Du kopieren oder per Mail schicken kannst. Damit oder über „Passwort vergessen“ setzt die Person ihr Passwort. Der alte Einladungslink wird ungültig.' },
      { label: 'Absagen (Einladung)', text: 'Bei Eingeladenen: zieht die Einladung zurück.' },
      { label: 'Detail-Dialog: Tab Konto', text: 'Hier änderst du Vorname, Nachname, Rufname und die weiteren Kontofelder. Felder, die du nicht ändern darfst, siehst du nur als Text. Mit Schloss-Symbol gekennzeichnete Felder werden verschlüsselt gespeichert.' },
      { label: 'Rolle (im Detail-Dialog)', text: 'Dropdown zum Ändern der Rolle. Nur sichtbar, wenn du Rollen vergeben darfst.' },
      { label: 'Konto speichern', text: 'Speichert die Änderungen im Tab Konto und schließt den Dialog.' },
      { label: 'Abbrechen / Schließen (Detail-Dialog)', text: 'Schließt den Dialog. Nicht gespeicherte Änderungen im Tab Konto gehen verloren.' },
      { label: 'Detail-Dialog: Tab Charaktere', text: 'Zeigt die Charaktere des Mitglieds mit ihren Events, die Zahl steht im Tab-Titel. Mit dem Recht, Status frei zu setzen, kannst du jeden Charakter aufklappen, bearbeiten und mit „Speichern“ sichern (auch interne Felder nur für Orga).' },
      { label: 'Charakter anlegen', text: 'Nur für Admins und Moderatoren: legt im Konto der Person einen neuen Charakter an. Name ist Pflicht.' },
      { label: 'Detail-Dialog: Tab Anmeldungen', text: 'Nur für Admins, Moderatoren und Personen mit dem Recht, Status frei zu setzen. Zeigt alle Anmeldungen mit Event, Con-Rolle, Sonderrollen, Extras und Status.' },
      { label: 'Detail-Dialog: E-Mail-Adresse (Login)', text: 'Nur für Admins. Trägt eine E-Mail-Adresse nach (z. B. bei Personen ohne E-Mail) oder ändert sie. Die Adresse ist zugleich der Login. Alte Zugangslinks werden dabei ungültig; danach kannst Du direkt einen neuen Zugangslink an die neue Adresse schicken.' },
      { label: 'Nr. (Mitgliedsnummer)', text: 'Jedes Konto hat eine feste, eindeutige Nummer, fortlaufend in der Reihenfolge der Kontoanlage. Sie ändert sich nie, steht im Detail-Titel und im CSV-Export und lässt sich suchen (Zahl ins Suchfeld eingeben, z. B. 42 oder #42). Eingeladene haben noch keine Nummer.' },
      { label: 'Detail-Dialog: Tab E-Mails', text: 'Nur für Admins. Die letzten automatischen E-Mails an diese Person mit Ergebnis (versendet, fehlgeschlagen, nicht versendet), auch die vor der Kontoanlage, z. B. die Einladung. Hilft bei „Ich habe keine Mail bekommen“.' },
      { label: 'Rolle (im Detail-Dialog, Tab Anmeldungen)', text: 'Nur mit dem Recht zum Status-Ändern. Ändert die Rolle der Anmeldung, zum Beispiel SC zu NSC oder umgekehrt. Dabei wird die Grenze der neuen Rolle geprüft: Ist die NSC-Grenze (oder die Gesamtgrenze) erreicht, geht der Wechsel nicht, und es erscheint eine Meldung. Klappt er, wird der alte Platz frei und ein wartender Mensch rückt nach. Der Charakter bleibt der Anmeldung zugeordnet.' },
      { label: 'Status (Anmeldung)', text: 'Dropdown pro Anmeldung, wie in der Liste: ändert den Anmeldestatus. Bei riskanten Wechseln (Zurücksetzen, Überspringen, Absagen) kommt eine Rückfrage.' },
      { label: 'Bearbeiten (Anmeldung)', text: 'Klappt Einverständnis-Hinweis, Sonderrollen und Anmeldefelder zum Ändern auf.' },
      { label: 'Anmeldedaten speichern', text: 'Speichert nur geänderte Felder und Sonderrollen der Anmeldung. Ohne Änderung passiert nichts.' },
      { label: 'Für ein Event anmelden', text: 'Nur für Admins und Moderatoren. Meldet das Mitglied für ein Event an, bei dem es noch nicht angemeldet ist. Du wählst Event, Rolle (SC, NSC, Helfer, Hilfs-Orga, Orga) und je nach Rolle Charakter, NSC-Angaben, Teilnahmegruppe und Extras. „Anmelden“ speichert.' },
      { label: 'Neues Mitglied einladen (Dialog)', text: 'Pflicht sind Vorname, Nachname und E-Mail. Optional sind Rufname, Veranstaltung (meldet direkt an), Rolle (nur wenn du Rollen vergeben darfst; sonst „sc“) und weitere Kontofelder.' },
      { label: 'Per E-Mail versenden', text: 'Haken im Einladungs-Dialog. Ohne Haken wird keine Mail verschickt und du bekommst nur den Link zum Weitergeben.' },
      { label: 'Einladung senden', text: 'Legt die Einladung an. Danach erscheint der Einladungslink unter der Tabelle. Schlägt die Mail fehl, bekommst du einen Hinweis; dann „Erneut senden“ nutzen.' },
      { label: 'Einladungslink / Zugriffslink (Feld unter der Tabelle)', text: 'Zeigt den zuletzt erzeugten Link. „Kopieren“ legt ihn in die Zwischenablage. „Per E-Mail senden“ gibt es nur beim Zugriffslink und schickt ihn an die Person.' },
      { label: 'Mitglieder aus CSV importieren (Dialog)', text: 'Zeigt die Vorschau mit Zeilen, E-Mail und Ergebnis (Neu, Aktualisieren, Fehler) sowie ignorierte Spalten. Neue Mitglieder erhalten eine Einladung, Passwörter werden nie importiert.' },
      { label: 'Einladungen per E-Mail versenden (Import)', text: 'Haken im Import-Dialog: schickt den neuen Mitgliedern die Einladung per Mail.' },
      { label: 'Importieren', text: 'Führt den Import aus. Gesperrt, solange Fehler in der Vorschau stehen oder nichts zu tun ist; es wird alles oder nichts übernommen.' }
    ]
  },
  '/admin/groups.html': {
    title: 'Rollen',
    anchor: 'rollen',
    intro: 'Nur für Admins: Hier legst du fest, welche Menüs, Felder und Sonderrechte jede Rolle hat.',
    items: [
      { label: 'Rollenliste', text: 'Zeigt Name, Schlüssel, sichtbare Menüs und ob die Rolle Charaktere bearbeiten darf.' },
      { label: 'Spalte Schlüssel', text: 'Der interne Kurzname der Rolle. Er wird beim Anlegen festgelegt und lässt sich danach nicht mehr ändern.' },
      { label: 'Geschützt', text: 'Systemrollen sind geschützt und lassen sich weder bearbeiten noch löschen.' },
      { label: 'Bearbeiten', text: 'Öffnet die Rolle im Dialog. Der Schlüssel bleibt gesperrt.' },
      { label: 'Löschen', text: 'Löscht die Rolle nach Rückfrage endgültig.' },
      { label: 'Als diese Rolle betrachten', text: 'Zeigt dir das Tool so, wie Mitglieder dieser Rolle es sehen, und öffnet dein Dashboard. Praktisch, um Rechte zu prüfen.' },
      { label: 'Neue Rolle anlegen', text: 'Öffnet den leeren Dialog für eine neue Rolle.' },
      { label: 'Name', text: 'Der angezeigte Name der Rolle. Pflichtfeld.' },
      { label: 'Schlüssel', text: 'Eindeutiger interner Name, nur Kleinbuchstaben, Zahlen und Unterstrich. Pflichtfeld, nur beim Anlegen änderbar.' },
      { label: 'Sichtbare Menüs', text: 'Welche Menüpunkte die Rolle sieht: Konto, Mitglieder, Events, Check-In und Taverne (Add-on).' },
      { label: 'Bearbeitbare Account-Felder', text: 'Welche Felder die Rolle in der Mitgliederverwaltung ändern darf. „Rolle“ erlaubt, Rollen zu vergeben; dazu kommen alle Konto- und Anmeldefelder.' },
      { label: 'Darf die Mitgliederliste als CSV exportieren', text: 'Schaltet den Button „CSV exportieren“ auf der Mitgliederseite frei. Der Export enthält die Konto-Felder, die die Rolle sehen darf.' },
      { label: 'Darf auch sensible Felder exportieren', text: 'Erlaubt zusätzlich den Export sensibler Felder wie Gesundheitshinweise.' },
      { label: 'Darf die Datenbank offline verwenden', text: 'Erlaubt das Umschalten zwischen Online und Offline und den Datenabgleich.' },
      { label: 'Darf Check-In-Status frei setzen und alle Charakterfelder sehen', text: 'Admin-, Orga- und Spielleitungs-Funktion: Status von Anmeldungen frei ändern und alle Charakterfelder sehen und bearbeiten.' },
      { label: 'Darf Charaktere anderer Mitglieder bearbeiten', text: 'Die Rolle darf Charaktere von anderen Mitgliedern ändern. In der Liste steht das als „Charaktere bearbeiten“ Ja oder Nein.' },
      { label: 'Speichern / Änderungen speichern', text: 'Legt die Rolle an bzw. speichert deine Änderungen.' },
      { label: 'Abbrechen', text: 'Schließt den Dialog ohne zu speichern.' }
    ]
  },
  '/admin/audit.html': {
    title: 'Protokoll',
    anchor: 'protokoll',
    intro: 'Nur für Admins: eine Liste wichtiger Ereignisse im System, neueste zuerst. Kleine Änderungen wie Profil, Felder oder Texte werden nicht protokolliert.',
    items: [
      { label: 'Kategorie', text: 'Filtert die Liste: Alle Ereignisse, Konten & Rollen, Charaktere, Anmeldungen & Check-in, Zahlungen, Gruppen, Zugangs- & Einladungslinks, Exporte & Backups oder Offline-Betrieb & Datenschutz.' },
      { label: 'Zeitpunkt', text: 'Datum und Uhrzeit des Ereignisses.' },
      { label: 'Wer', text: 'Die Person, die die Aktion ausgelöst hat. „–“ heißt, dass kein Name bekannt ist.' },
      { label: 'Aktion', text: 'Art des Ereignisses, zum Beispiel Konto registriert, Rolle geändert, Zahlung eingegangen oder Export Mitgliederliste.' },
      { label: 'Details', text: 'Zusatzinfos zum Ereignis, etwa betroffene Person, Event, Betrag, alter und neuer Wert oder die Anzahl exportierter Einträge.' },
      { label: 'Anzeigeumfang', text: 'Es werden die letzten 1000 Einträge geladen. Die Kategorie filtert nur diese.' }
    ]
  }
};
